window.APP_DB = {
  "Lesson 1A - Greetings and Farewells": [
    ["Bom dia!", "<span style='font-weight:800;color:var(--rv-pale)'>Good morning!</span> — use 6am to 12pm to start a chat — say bong DEE-ah — formal, safe with strangers — Marta to Leo first line"],
    ["Boa tarde!", "<span style='font-weight:800;color:var(--rv-pale)'>Good afternoon!</span> — use 12pm to 6pm — say BOH-ah TAR-jee — formal greeting"],
    ["Boa noite!", "<span style='font-weight:800;color:var(--rv-pale)'>Good evening and Good night!</span> — after 6pm, hello and goodbye — say BOH-ah NOY-chee"],
    ["Oi!", "<span style='font-weight:800;color:var(--rv-pale)'>Hi!</span> — informal, friends and people your age — very Brazilian — say oy — less formal than Olá"],
    ["Olá!", "<span style='font-weight:800;color:var(--rv-pale)'>Hello!</span> — neutral, works anywhere — say oh-LAH — a bit more polite than Oi"],
    ["Adeus!", "<span style='font-weight:800;color:var(--rv-pale)'>Goodbye!</span> — formal and final, rare daily — say ah-DEH-oos — prefer Tchau in Brazil"],
    ["Tchau!", "<span style='font-weight:800;color:var(--rv-pale)'>Bye!</span> — number 1 goodbye in Brazil, casual — say chow — from Italian ciao"],
    ["Até logo!", "<span style='font-weight:800;color:var(--rv-pale)'>See you later!</span> — informal farewell, you will meet again — say ah-TEH LOH-goo — Marta to Leo"],
    ["Até mais!", "<span style='font-weight:800;color:var(--rv-pale)'>See you! Bye for now!</span> — casual, very common — say ah-TEH mice — short for Até mais tarde"]
  ],
  "Lesson 1B - Courtesy Expressions": [
    ["Bem-vindo!", "<span style='font-weight:800;color:var(--rv-pale)'>Welcome! said to a man</span> — ends in -o because HE is male — Leo to a man — listener gender decides"],
    ["Bem-vinda!", "<span style='font-weight:800;color:var(--rv-pale)'>Welcome! said to a woman</span> — ends in -a because SHE is female — Seja bem-vinda Marta — listener gender decides"],
    ["Obrigado!", "<span style='font-weight:800;color:var(--rv-pale)'>Thank you! said BY a man</span> — ends in -o because SPEAKER is male — Leo says Obrigado — speaker gender decides"],
    ["Obrigada!", "<span style='font-weight:800;color:var(--rv-pale)'>Thank you! said BY a woman</span> — ends in -a because SPEAKER is female — Marta says Obrigada — speaker gender decides"],
    ["Muito obrigado!", "<span style='font-weight:800;color:var(--rv-pale)'>Thank you very much! said BY a man</span> — muito adds force — speaker male"],
    ["Muito obrigada!", "<span style='font-weight:800;color:var(--rv-pale)'>Thank you very much! said BY a woman</span> — Marta: muito obrigada Ze — speaker female"],
    ["Prazer em conhecê-lo!", "<span style='font-weight:800;color:var(--rv-pale)'>Nice to meet you! to a man</span> — -lo means him — say pra-ZER — to him"],
    ["Prazer em conhecê-la!", "<span style='font-weight:800;color:var(--rv-pale)'>Nice to meet you! to a woman</span> — -la means her — to her"],
    ["Muito prazer!", "<span style='font-weight:800;color:var(--rv-pale)'>Nice to meet you!</span> — no gender change, works for all — after introductions — Leo: Muito prazer"],
    ["Por favor...", "<span style='font-weight:800;color:var(--rv-pale)'>Please...</span> — no gender change, universal — say poor fah-VOR — Marta to taxi driver"],
    ["Por gentileza...", "<span style='font-weight:800;color:var(--rv-pale)'>Kindly... Please...</span> — more formal than Por favor — on the phone: pode repetir por gentileza"],
    ["Com licença...", "<span style='font-weight:800;color:var(--rv-pale)'>Excuse me...</span> — to pass or get attention — say kong lee-SEN-sah"],
    ["Desculpa!", "<span style='font-weight:800;color:var(--rv-pale)'>Sorry! informal</span> — friends and peers — Marta: Desculpa mas estou cansada — formal is Desculpe"],
    ["Seja bem-vinda!", "<span style='font-weight:800;color:var(--rv-pale)'>Be welcome! to a woman</span> — Leo welcomes Marta — seja is be, -a for her"]
  ],
  "Lesson 1C - Ser and Pronouns": [
    ["Eu", "<span style='font-weight:800;color:var(--rv-pale)'>I</span> — 1st person singular — Eu sou Marta — I am Marta"],
    ["Tu", "<span style='font-weight:800;color:var(--rv-pale)'>You informal</span> — regional, south and northeast — most of Brazil uses Você — verbs differ: tu és vs você é"],
    ["Você", "<span style='font-weight:800;color:var(--rv-pale)'>You</span> — number 1 you in Brazil — use with strangers and friends — verbs in 3rd form: você é"],
    ["Ele", "<span style='font-weight:800;color:var(--rv-pale)'>He</span> — 3rd masculine — Ele é estudante — He is a student"],
    ["Ela", "<span style='font-weight:800;color:var(--rv-pale)'>She</span> — 3rd feminine — Ela é estudante — She is a student"],
    ["Nós", "<span style='font-weight:800;color:var(--rv-pale)'>We</span> — 1st plural — Nós somos amigos — We are friends — say nosh with soft s"],
    ["Vós", "<span style='font-weight:800;color:var(--rv-pale)'>You old formal plural</span> — almost dead in speech, Bible and church — know it, do not use daily"],
    ["Eles", "<span style='font-weight:800;color:var(--rv-pale)'>They masculine or mixed</span> — Eles são brasileiros — They are Brazilian"],
    ["Elas", "<span style='font-weight:800;color:var(--rv-pale)'>They feminine only</span> — all women group — Elas são brasileiras"],
    ["Eu sou", "<span style='font-weight:800;color:var(--rv-pale)'>I am — sou</span> — identity and origin — Eu sou brasileiro or just Sou brasileiro — pronoun can drop"],
    ["Tu és", "<span style='font-weight:800;color:var(--rv-pale)'>You are — és</span> — Tu és estrangeira — regional informal — pronoun can drop: És estrangeira"],
    ["Ele é / Ela é", "<span style='font-weight:800;color:var(--rv-pale)'>He is / She is — é</span> — Ela é estudante — say eh — pronoun can drop: É estudante"],
    ["Nós somos", "<span style='font-weight:800;color:var(--rv-pale)'>We are — somos</span> — Nós somos amigos — say SOH-moosh"],
    ["Vós sois", "<span style='font-weight:800;color:var(--rv-pale)'>You are — sois</span> — very formal archaic, rare — just recognize it"],
    ["Eles são / Elas são", "<span style='font-weight:800;color:var(--rv-pale)'>They are — são</span> — Eles são brasileiros — nasal sow with tilde — pronoun can drop"],
    ["Sou a Marta", "<span style='font-weight:800;color:var(--rv-pale)'>I am Marta</span> — sou without Eu is natural — Marta: Sou a nova moradora do 702 — English needs I, Portuguese can drop it"]
  ],
  "Lesson 1D - Alphabet A to Z": [
    ["A", "<span style='font-weight:800;color:var(--rv-pale)'>a [a]</span> — ah as in father — Amigo friend, Amanhã tomorrow"],
    ["B", "<span style='font-weight:800;color:var(--rv-pale)'>be [be]</span> — beh — Bala candy, Brasil"],
    ["C", "<span style='font-weight:800;color:var(--rv-pale)'>ce [se]</span> — seh — Casa house, Cebola onion, Cinema, Coração, Curioso — C changes sound by vowel"],
    ["D", "<span style='font-weight:800;color:var(--rv-pale)'>de [de]</span> — deh — Dia day, Doce sweet"],
    ["E", "<span style='font-weight:800;color:var(--rv-pale)'>e [open and closed]</span> — eh — Estudante student, Ego — can be open or closed"],
    ["F", "<span style='font-weight:800;color:var(--rv-pale)'>efe [efi]</span> — eh-fee — Felicidade happiness, Fome hunger"],
    ["G", "<span style='font-weight:800;color:var(--rv-pale)'>ge [zhe]</span> — zheh — Gato cat, Gente people, Guerra war — G changes before e and i"],
    ["H", "<span style='font-weight:800;color:var(--rv-pale)'>aga — always silent at start</span> — História history, Hoje today — never say H, say oh-jee not ho-jee"],
    ["I", "<span style='font-weight:800;color:var(--rv-pale)'>i [ee]</span> — ee as in see — Inteligência, Ideia idea"],
    ["J", "<span style='font-weight:800;color:var(--rv-pale)'>jota [zhota]</span> — zhota — Janela window, Jeito way, Jovem young"],
    ["K", "<span style='font-weight:800;color:var(--rv-pale)'>ca [ka]</span> — kah — Kiwi, Karaoke — only foreign words"],
    ["L", "<span style='font-weight:800;color:var(--rv-pale)'>ele [eli]</span> — eh-lee — Livro book, Lata can"],
    ["M", "<span style='font-weight:800;color:var(--rv-pale)'>eme [emi]</span> — em-ee — Mala suitcase, Mercado market — Marta spells M-A-R-T-A"],
    ["N", "<span style='font-weight:800;color:var(--rv-pale)'>ene [eni]</span> — en-ee — Namorada girlfriend, Nuvem cloud"],
    ["O", "<span style='font-weight:800;color:var(--rv-pale)'>o [open and closed]</span> — aw and oh — Olho eye, Põe puts — open vs closed changes meaning"],
    ["P", "<span style='font-weight:800;color:var(--rv-pale)'>pe [pe]</span> — peh — Pedra stone, Profissão profession"],
    ["Q", "<span style='font-weight:800;color:var(--rv-pale)'>que [ke]</span> — keh — Queijo cheese, Quinta-feira Thursday — Q always with U"],
    ["R", "<span style='font-weight:800;color:var(--rv-pale)'>erre — guttural R</span> — eh-hee throaty — Região, Arroz rice, Coragem — single R soft, double RR strong"],
    ["S", "<span style='font-weight:800;color:var(--rv-pale)'>esse [esi]</span> — eh-see — Sala room, Sessão session, Cesto basket"],
    ["T", "<span style='font-weight:800;color:var(--rv-pale)'>te [te]</span> — teh — Telefone phone, Tia aunt — T before I sounds like chee in Brazil: Tia = CHEE-ah"],
    ["U", "<span style='font-weight:800;color:var(--rv-pale)'>u [oo]</span> — oo — Um a, Uniforme uniform"],
    ["V", "<span style='font-weight:800;color:var(--rv-pale)'>ve [ve]</span> — veh — Vizinha neighbor, Voz voice — V is soft, not W"],
    ["W", "<span style='font-weight:800;color:var(--rv-pale)'>dablio [dabliu]</span> — dah-blee-oo — Walter, Watt — only foreign words"],
    ["X", "<span style='font-weight:800;color:var(--rv-pale)'>xis [shees]</span> — shees — Xadrez chess, Taxi, Exemplo — X has 4 sounds, most tricky letter"],
    ["Y", "<span style='font-weight:800;color:var(--rv-pale)'>ipsilon</span> — eep-see-lon — Yuri — only foreign words"],
    ["Z", "<span style='font-weight:800;color:var(--rv-pale)'>ze [ze]</span> — zeh — Zebra, Zoológico zoo"],
    ["M-A-R-T-A", "<span style='font-weight:800;color:var(--rv-pale)'>Spelling your name</span> — É Marta M-A-R-T-A — use letter names to spell on bad phone lines — Marta to telefonista"]
  ],
  "Lesson 1E - Nouns Gender and Number": [
    ["o porteiro", "<span style='font-weight:800;color:var(--rv-pale)'>the doorman — masculine the</span> — o means the for him — o porteiro abriu a porta"],
    ["um porteiro", "<span style='font-weight:800;color:var(--rv-pale)'>a doorman — masculine a</span> — um means a for him — non-specific man"],
    ["a síndica", "<span style='font-weight:800;color:var(--rv-pale)'>the manager — feminine the</span> — a means the for her — a síndica organizou"],
    ["uma síndica", "<span style='font-weight:800;color:var(--rv-pale)'>a manager — feminine a</span> — uma means a for her — non-specific woman"],
    ["o estudante", "<span style='font-weight:800;color:var(--rv-pale)'>the male student — same word</span> — article shows gender, noun never changes — o shows he"],
    ["a estudante", "<span style='font-weight:800;color:var(--rv-pale)'>the female student — same word</span> — only A changes to show she — common of two genders"],
    ["o garoto", "<span style='font-weight:800;color:var(--rv-pale)'>the boy — -o to -a pair</span> — masculine base form"],
    ["a garota", "<span style='font-weight:800;color:var(--rv-pale)'>the girl — -o becomes -a</span> — change ending to make feminine — variable noun"],
    ["o lápis", "<span style='font-weight:800;color:var(--rv-pale)'>the pencil — always masculine</span> — never A lápis — ends in S but still HE — memorize"],
    ["a caneta", "<span style='font-weight:800;color:var(--rv-pale)'>the pen — always feminine</span> — never O caneta — ends in A and is SHE — memorize"],
    ["os porteiros", "<span style='font-weight:800;color:var(--rv-pale)'>the doormen — add S</span> — o becomes os, add S to noun — plural masculine the"],
    ["as síndicas", "<span style='font-weight:800;color:var(--rv-pale)'>the managers — add S</span> — a becomes as, add S — plural feminine the"],
    ["o menino / os meninos", "<span style='font-weight:800;color:var(--rv-pale)'>boy to boys — add S</span> — general plural rule: add S after vowel"],
    ["a menina / as meninas", "<span style='font-weight:800;color:var(--rv-pale)'>girl to girls — add S</span> — article and noun both get S"],
    ["um livro / uns livros", "<span style='font-weight:800;color:var(--rv-pale)'>a book to some books</span> — um to uns — indefinite plural means some"],
    ["uma mala / umas malas", "<span style='font-weight:800;color:var(--rv-pale)'>a suitcase to some suitcases</span> — uma to umas — Marta trouxe algumas malas"],
    ["Eu sou Marta", "<span style='font-weight:800;color:var(--rv-pale)'>I am Marta — Eu + sou + name</span> — pronoun plus SER plus noun — swap Marta for brasileira, escultora"]
  ],
  "Lesson 1F - Nationalities": [
    ["De onde você é?", "<span style='font-weight:800;color:var(--rv-pale)'>Where are you from?</span> — THE origin question — say jee OHN-jee — Leo to Marta and Rasmus — answer with Sou..."],
    ["Sou daqui da cidade", "<span style='font-weight:800;color:var(--rv-pale)'>I am from here in town</span> — Marta answer — daqui means from here — use SER for origin"],
    ["Sou brasileiro", "<span style='font-weight:800;color:var(--rv-pale)'>I am Brazilian — man speaking</span> — -o for him — Rasmus: Sou brasileiro"],
    ["Sou brasileira", "<span style='font-weight:800;color:var(--rv-pale)'>I am Brazilian — woman speaking</span> — -a for her — Marta would say brasileira"],
    ["Brasil - Brasileiro / Brasileira", "<span style='font-weight:800;color:var(--rv-pale)'>Brazil — Brazilian man and woman</span> — your host country"],
    ["Alemanha - Alemão / Alemã", "<span style='font-weight:800;color:var(--rv-pale)'>Germany — German</span> — -ao to -a pair — nasal AO"],
    ["Argentina - Argentino / Argentina", "<span style='font-weight:800;color:var(--rv-pale)'>Argentina — Argentine</span> — -o to -a"],
    ["Portugal - Português / Portuguesa", "<span style='font-weight:800;color:var(--rv-pale)'>Portugal — Portuguese</span> — different from Brasileiro — European vs Brazilian"],
    ["Suécia - Sueco / Sueca", "<span style='font-weight:800;color:var(--rv-pale)'>Sweden — Swedish</span> — Rasmus parents: meus pais vieram da Suécia — pais são suecos"],
    ["Estados Unidos - Estadunidense", "<span style='font-weight:800;color:var(--rv-pale)'>USA — American</span> — same word for man and woman — no change"],
    ["Inglaterra - Inglês / Inglesa", "<span style='font-weight:800;color:var(--rv-pale)'>England — English</span> — say eeng-LESH — s with sh sound"],
    ["França - Francês / Francesa", "<span style='font-weight:800;color:var(--rv-pale)'>France — French</span> — Dona Ana relógio veio da França"],
    ["Itália - Italiano / Italiana", "<span style='font-weight:800;color:var(--rv-pale)'>Italy — Italian</span>"],
    ["Espanha - Espanhol / Espanhola", "<span style='font-weight:800;color:var(--rv-pale)'>Spain — Spanish</span> — NH sounds like NY: espanhol = es-pan-YOL"],
    ["China - Chinês / Chinesa", "<span style='font-weight:800;color:var(--rv-pale)'>China — Chinese</span>"],
    ["Japão - Japonês / Japonesa", "<span style='font-weight:800;color:var(--rv-pale)'>Japan — Japanese</span> — nasal AO"],
    ["Meus pais vieram da Suécia", "<span style='font-weight:800;color:var(--rv-pale)'>My parents came from Sweden</span> — Rasmus family story — vieram is came, da is from the"]
  ],
  "Lesson 1G - Numbers 0 to 100": [
    ["zero", "<span style='font-weight:800;color:var(--rv-pale)'>0 — zero</span> — say ZEH-roo — start of phones and addresses"],
    ["um", "<span style='font-weight:800;color:var(--rv-pale)'>1 — um</span> — nasal oong — also A for masculine: um livro"],
    ["dois", "<span style='font-weight:800;color:var(--rv-pale)'>2 — dois</span> — say doysh"],
    ["três", "<span style='font-weight:800;color:var(--rv-pale)'>3 — três</span> — say trehsh with open E"],
    ["quatro", "<span style='font-weight:800;color:var(--rv-pale)'>4 — quatro</span>"],
    ["cinco", "<span style='font-weight:800;color:var(--rv-pale)'>5 — cinco</span> — say SEENG-koo"],
    ["seis", "<span style='font-weight:800;color:var(--rv-pale)'>6 — seis</span> — say saysh"],
    ["sete", "<span style='font-weight:800;color:var(--rv-pale)'>7 — sete</span> — say SEH-chee"],
    ["oito", "<span style='font-weight:800;color:var(--rv-pale)'>8 — oito</span> — say OY-too — vinte e oito pattern"],
    ["nove", "<span style='font-weight:800;color:var(--rv-pale)'>9 — nove</span> — say NOH-vee — oitenta e nove address"],
    ["dez", "<span style='font-weight:800;color:var(--rv-pale)'>10 — dez</span> — say dehsh"],
    ["onze", "<span style='font-weight:800;color:var(--rv-pale)'>11 — onze</span>"],
    ["doze", "<span style='font-weight:800;color:var(--rv-pale)'>12 — doze</span>"],
    ["treze", "<span style='font-weight:800;color:var(--rv-pale)'>13 — treze</span>"],
    ["quatorze", "<span style='font-weight:800;color:var(--rv-pale)'>14 — quatorze</span> — Luiza: Tenho 14 anos — say kwa-TOR-zee"],
    ["quinze", "<span style='font-weight:800;color:var(--rv-pale)'>15 — quinze</span>"],
    ["dezesseis", "<span style='font-weight:800;color:var(--rv-pale)'>16 — dezesseis</span> — deh-zeh-SAYSH — dez plus seis joined"],
    ["dezessete", "<span style='font-weight:800;color:var(--rv-pale)'>17 — dezessete</span>"],
    ["dezoito", "<span style='font-weight:800;color:var(--rv-pale)'>18 — dezoito</span>"],
    ["dezenove", "<span style='font-weight:800;color:var(--rv-pale)'>19 — dezenove</span>"],
    ["vinte", "<span style='font-weight:800;color:var(--rv-pale)'>20 — vinte</span> — say VEEN-chee"],
    ["trinta", "<span style='font-weight:800;color:var(--rv-pale)'>30 — trinta</span>"],
    ["quarenta", "<span style='font-weight:800;color:var(--rv-pale)'>40 — quarenta</span> — quarenta e três age — say kwa-REN-tah"],
    ["cinquenta", "<span style='font-weight:800;color:var(--rv-pale)'>50 — cinquenta</span>"],
    ["sessenta", "<span style='font-weight:800;color:var(--rv-pale)'>60 — sessenta</span>"],
    ["setenta", "<span style='font-weight:800;color:var(--rv-pale)'>70 — setenta</span>"],
    ["oitenta", "<span style='font-weight:800;color:var(--rv-pale)'>80 — oitenta</span> — oitenta e nove number 89 — Marta address"],
    ["noventa", "<span style='font-weight:800;color:var(--rv-pale)'>90 — noventa</span>"],
    ["cem", "<span style='font-weight:800;color:var(--rv-pale)'>100 — cem</span> — say sayng — exactly 100, 101 is cento e um"],
    ["vinte e um", "<span style='font-weight:800;color:var(--rv-pale)'>21 — ten plus E plus one</span> — rule: dezena E unidade — vinte E oito, trinta E dois"],
    ["quarenta e três", "<span style='font-weight:800;color:var(--rv-pale)'>43 — forty and three</span> — Rasmus: Tenho quarenta e três anos — E joins them"],
    ["oitenta e nove", "<span style='font-weight:800;color:var(--rv-pale)'>89 — eighty and nine</span> — Rua dos Presidentes número oitenta e nove — Marta taxi"],
    ["Quantos anos você tem?", "<span style='font-weight:800;color:var(--rv-pale)'>How old are you?</span> — literally How many years you have — uses TER not SER — Leo to Rasmus"],
    ["Tenho quarenta e três anos", "<span style='font-weight:800;color:var(--rv-pale)'>I am 43 years old</span> — literally I have 43 years — Portuguese HAS age, English IS age"]
  ],
  "Lesson 1H - Estar and Feelings": [
    ["Eu estou bem", "<span style='font-weight:800;color:var(--rv-pale)'>I am well — estou</span> — temporary state, not identity — SER is who you are, ESTAR is how you are"],
    ["Tu estás cansado", "<span style='font-weight:800;color:var(--rv-pale)'>You are tired — estás</span> — change -o to -a for woman: cansada — regional tu"],
    ["Ele está / Ela está", "<span style='font-weight:800;color:var(--rv-pale)'>He is / She is — está</span> — Ele está ansioso com a viagem — He is anxious about the trip"],
    ["Nós estamos felizes", "<span style='font-weight:800;color:var(--rv-pale)'>We are happy — estamos</span> — Estamos felizes com a chegada — happy about arrival"],
    ["Elas estão famintas", "<span style='font-weight:800;color:var(--rv-pale)'>They are starving — estão</span> — nasal TOW with tilde — feminine famintas"],
    ["Estou um pouco cansada", "<span style='font-weight:800;color:var(--rv-pale)'>I am a bit tired — woman speaking</span> — Marta tired line — -a because Marta is SHE — man says cansado"],
    ["Estar vs Ser", "<span style='font-weight:800;color:var(--rv-pale)'>Both mean TO BE in English</span> — SER is permanent: sou brasileiro — ESTAR is temporary: estou cansada — biggest English-speaker trap"],
    ["cansado / cansada", "<span style='font-weight:800;color:var(--rv-pale)'>tired man and woman</span> — feeling word changes with YOU — Marta cansada, Leo cansado"],
    ["bem / feliz / ansioso", "<span style='font-weight:800;color:var(--rv-pale)'>well, happy, anxious</span> — mood words with ESTAR — estou bem, estamos felizes, está ansioso"]
  ],
  "Lesson 2A - Question Words": [
    ["O que voce estuda?", "<span style='font-weight:800;color:var(--rv-pale)'>What do you study?</span> — O que starts a question about things, work, study — say oo kee"],
    ["Voce estuda o que?", "<span style='font-weight:800;color:var(--rv-pale)'>You study what?</span> — ...o que at END also works — same meaning, spoken style — question mark only at end, no upside-down"],
    ["Quem e voce?", "<span style='font-weight:800;color:var(--rv-pale)'>Who are you?</span> — Quem asks about people — Quem e...? Who is...?"],
    ["Qual e o numero?", "<span style='font-weight:800;color:var(--rv-pale)'>What is the number?</span> — Qual for one: Qual e o numero do seu telefone — choose one"],
    ["Quais sao os numeros?", "<span style='font-weight:800;color:var(--rv-pale)'>What are the numbers?</span> — Quais for many: Quais sao os numeros — add S for plural"],
    ["Onde voce mora?", "<span style='font-weight:800;color:var(--rv-pale)'>Where do you live?</span> — Onde asks place — THE key of Lesson 2 and 3 — Luiza: Onde posso deixar a cesta"],
    ["Aonde voce vai?", "<span style='font-weight:800;color:var(--rv-pale)'>Where are you going?</span> — Aonde adds movement TO — Onde is where, Aonde is where TO"],
    ["Em que rua voce mora?", "<span style='font-weight:800;color:var(--rv-pale)'>On which street do you live?</span> — Em que equals Onde for streets — Em que rua...?"],
    ["Quando comecam as aulas?", "<span style='font-weight:800;color:var(--rv-pale)'>When do classes start?</span> — Quando asks time — say KWAN-doo"],
    ["Como voce esta?", "<span style='font-weight:800;color:var(--rv-pale)'>How are you?</span> — Como asks how and state — Luiza: Ola Tudo bem is same family"],
    ["Quanto custa?", "<span style='font-weight:800;color:var(--rv-pale)'>How much does it cost?</span> — Quanto for one price and amount — say KWAN-too"],
    ["Quantos moram nesta casa?", "<span style='font-weight:800;color:var(--rv-pale)'>How many live in this house?</span> — Quantos for countable people — Marta: Quantos anos voce tem — add S for many"],
    ["Onde posso deixar a cesta?", "<span style='font-weight:800;color:var(--rv-pale)'>Where can I leave the basket?</span> — Luiza at door — Onde plus action — your model for asking place"],
    ["Quantos anos voce tem?", "<span style='font-weight:800;color:var(--rv-pale)'>How old are you?</span> — Marta to Luiza — uses TER: tem — answer Tenho 14 anos"]
  ],
  "Lesson 2B - Formal and Informal You": [
    ["senhor", "<span style='font-weight:800;color:var(--rv-pale)'>Sir / Mister — formal man</span> — use with older men and strangers — always with O: O senhor — Rudinei to known man"],
    ["senhora", "<span style='font-weight:800;color:var(--rv-pale)'>Madam — formal woman</span> — use with older women — always with A: A senhora quer...? — Rudinei to Dona Ana"],
    ["senhores / senhoras", "<span style='font-weight:800;color:var(--rv-pale)'>Gentlemen / Ladies — plural formal</span> — add ES for many — Onde as senhoras moram"],
    ["voce", "<span style='font-weight:800;color:var(--rv-pale)'>You informal-friendly</span> — friends, peers, most of Brazil — verbs in 3rd form: Voce esta bem, not estas"],
    ["voces", "<span style='font-weight:800;color:var(--rv-pale)'>You all — plural you</span> — Onde voces moram — Nos moramos..."],
    ["dona Ana", "<span style='font-weight:800;color:var(--rv-pale)'>Mrs Ana — warm formal</span> — Dona plus first name equals Senhora — O que e isso Dona Ana"],
    ["tu vs voce", "<span style='font-weight:800;color:var(--rv-pale)'>Tu is regional you</span> — south and northeast use tu — most use voce — same person, different verb: tu moras vs voce mora"]
  ],
  "Lesson 2C - Possessives": [
    ["Me chamo Luiza", "<span style='font-weight:800;color:var(--rv-pale)'>I am called Luiza — spoken intro</span> — Luiza at door — oral style — written style is Meu nome e Luiza"],
    ["Meu nome e...", "<span style='font-weight:800;color:var(--rv-pale)'>My name is...</span> — meu is MY for masculine word: Meu nome, Meu endereco — meu plus masculine singular"],
    ["Meu endereco e Rua das Palmeiras 30", "<span style='font-weight:800;color:var(--rv-pale)'>My address is...</span> — meu before masculine endereco — model for your address"],
    ["Minhas malas nao chegaram", "<span style='font-weight:800;color:var(--rv-pale)'>My suitcases have not arrived</span> — minhas for feminine plural malas — possessive matches THING not you"],
    ["Teus vizinhos sao simpaticos", "<span style='font-weight:800;color:var(--rv-pale)'>Your neighbors are nice — tu form</span> — teus for masculine plural — regional, most say seus"],
    ["Tua familia e receptiva", "<span style='font-weight:800;color:var(--rv-pale)'>Your family is welcoming — tu form</span> — tua for feminine singular"],
    ["Seu apartamento e grande", "<span style='font-weight:800;color:var(--rv-pale)'>Your apartment is big — voce form</span> — seu is YOUR for him/her/you — most common YOUR"],
    ["Suas historias sao incriveis", "<span style='font-weight:800;color:var(--rv-pale)'>Your stories are amazing</span> — suas for feminine plural historias"],
    ["Nosso condominio e cuidado", "<span style='font-weight:800;color:var(--rv-pale)'>Our condo is well kept</span> — nosso for masculine: Nosso condominio — we-our"],
    ["Nossa escola promove leitura", "<span style='font-weight:800;color:var(--rv-pale)'>Our school promotes reading</span> — nossa for feminine escola"],
    ["seus segredos / sua avo", "<span style='font-weight:800;color:var(--rv-pale)'>their secrets / his grandma</span> — Luiza e Marta tem SEUS segredos — Eles moram com SUA avo — seu covers his her their you"]
  ],
  "Lesson 2D - Verb Ter To Have": [
    ["Eu tenho trinta anos", "<span style='font-weight:800;color:var(--rv-pale)'>I am 30 — literally I have 30</span> — tenho is I have — age uses HAVE in Portuguese"],
    ["Tu tens quantos anos?", "<span style='font-weight:800;color:var(--rv-pale)'>How old are you — tu form</span> — tens with S for tu — regional"],
    ["Ele tem cabelos compridos", "<span style='font-weight:800;color:var(--rv-pale)'>He has long hair — tem</span> — tem no hat for he/she/you — characteristic"],
    ["Nos temos a mesma profissao", "<span style='font-weight:800;color:var(--rv-pale)'>We have the same job — temos</span> — we-have"],
    ["Os meninos tem as mesmas ideias", "<span style='font-weight:800;color:var(--rv-pale)'>The boys have the same ideas — tem with hat</span> — eles TEM with ^ — ele tem vs eles tem — hat marks plural"],
    ["Tenho 14 anos!", "<span style='font-weight:800;color:var(--rv-pale)'>I am 14! — Luiza answer</span> — drop Eu: Tenho alone means I — Marta asked Quantos anos voce tem"],
    ["Que olhos lindos ele tem!", "<span style='font-weight:800;color:var(--rv-pale)'>What beautiful eyes he has!</span> — TER for features — compliment pattern"]
  ],
  "Lesson 2E - Verb Morar To Live": [
    ["Eu moro em Portugal", "<span style='font-weight:800;color:var(--rv-pale)'>I live in Portugal — moro</span> — I-form ends in O — drop Eu: Moro em..."],
    ["Tu moras em Porto Alegre?", "<span style='font-weight:800;color:var(--rv-pale)'>Do you live in Porto Alegre — tu form</span> — tu adds S: moras — regional"],
    ["Ele mora na Colombia", "<span style='font-weight:800;color:var(--rv-pale)'>He lives in Colombia — mora</span> — he/she/you form — na is in the"],
    ["Nos moramos no Condominio Brasil", "<span style='font-weight:800;color:var(--rv-pale)'>We live in Condominium Brasil — moramos</span> — we-form with MOS"],
    ["Eles moram na avenida", "<span style='font-weight:800;color:var(--rv-pale)'>They live on the avenue — moram</span> — they-form ends in AM"],
    ["Onde voce mora?", "<span style='font-weight:800;color:var(--rv-pale)'>Where do you live? — THE address question</span> — answer Moro na Rua... — pair them always"],
    ["Moro na Rua dos Presidentes 85", "<span style='font-weight:800;color:var(--rv-pale)'>I live at 85 Presidents Street</span> — model answer — Moro plus NA plus street — Marta street"],
    ["Onde voces moram?", "<span style='font-weight:800;color:var(--rv-pale)'>Where do you all live?</span> — plural you — answer Nos moramos na Rua..."],
    ["Elas moram no bairro Julio", "<span style='font-weight:800;color:var(--rv-pale)'>They live in Julio district — formal ladies</span> — Onde as senhoras moram — Elas moram..."]
  ],
  "Lesson 2F - Asking for Help": [
    ["Eu nao falo portugues", "<span style='font-weight:800;color:var(--rv-pale)'>I do not speak Portuguese — survival line 1</span> — say now FAH-loo — use day 1 in Brazil"],
    ["Voce pode me explicar?", "<span style='font-weight:800;color:var(--rv-pale)'>Can you explain to me?</span> — polite request — pode means can"],
    ["Por gentileza me ajudar?", "<span style='font-weight:800;color:var(--rv-pale)'>Could you help me please? — formal</span> — Por gentileza softens any ask"],
    ["Voce pode me auxiliar?", "<span style='font-weight:800;color:var(--rv-pale)'>Can you assist me in this?</span> — a bit more formal than ajudar"],
    ["Eu nao entendi. Pode repetir?", "<span style='font-weight:800;color:var(--rv-pale)'>I did not understand. Can you repeat?</span> — Marta phone scene needs this — most useful classroom line"],
    ["Por favor fale mais devagar?", "<span style='font-weight:800;color:var(--rv-pale)'>Please speak more slowly?</span> — devagar is slowly — say dee-vah-GAR — lifesaver"],
    ["O que significa essa palavra?", "<span style='font-weight:800;color:var(--rv-pale)'>What does this word mean?</span> — point and ask — significa means means"],
    ["Eu nao compreendo o que voce fala", "<span style='font-weight:800;color:var(--rv-pale)'>I do not understand what you say</span> — stronger than nao entendi — honest and polite with Por favor"]
  ],
  "Lesson 3A - Ficar vs Estar": [
    ["Onde fica esse mercadinho?", "<span style='font-weight:800;color:var(--rv-pale)'>Where is that little market? — THE place question</span> — Marta to Leo — fica for PLACES — say FEE-kah"],
    ["Ele fica bem na esquina", "<span style='font-weight:800;color:var(--rv-pale)'>It is right on the corner — permanent place</span> — Leo answer — ele for market — FICAR is fixed address"],
    ["O supermercado fica ao lado", "<span style='font-weight:800;color:var(--rv-pale)'>The supermarket is next to — fica</span> — buildings use FICAR — ao lado is next to"],
    ["As lojas ficam na quadra", "<span style='font-weight:800;color:var(--rv-pale)'>The shops are on the block — ficam plural</span> — one shop fica, many ficam — ele vs eles"],
    ["Eu estou na farmacia", "<span style='font-weight:800;color:var(--rv-pale)'>I am at the pharmacy — ESTAR for people</span> — temporary where-I-am — ESTOU for I"],
    ["O celular esta na mesa", "<span style='font-weight:800;color:var(--rv-pale)'>The phone is on the table — ESTAR for things</span> — movable object uses ESTAR not FICAR"],
    ["Onde voce esta?", "<span style='font-weight:800;color:var(--rv-pale)'>Where are you? — for a PERSON</span> — answer Estou em frente ao predio — Onde plus ESTAR is people"],
    ["Estamos em frente ao predio", "<span style='font-weight:800;color:var(--rv-pale)'>We are in front of the building</span> — estamos for we — em frente is in front"],
    ["Ficar is fixed, Estar is moving", "<span style='font-weight:800;color:var(--rv-pale)'>FICAR is address, ESTAR is position</span> — shop FICA, you ESTAO — Lesson 1 Estar was feelings, now it is place too"]
  ],
  "Lesson 3B - Shops and Places": [
    ["Acougue", "<span style='font-weight:800;color:var(--rv-pale)'>Butcher shop</span> — meat place — say ah-soh-GEE"],
    ["Banco", "<span style='font-weight:800;color:var(--rv-pale)'>Bank</span> — O predio fica ao lado da agencia bancaria"],
    ["Bar", "<span style='font-weight:800;color:var(--rv-pale)'>Bar</span> — same as English"],
    ["Cabeleireiro", "<span style='font-weight:800;color:var(--rv-pale)'>Hairdresser</span> — long word: cah-beh-lay-RAY-roo"],
    ["Fruteira", "<span style='font-weight:800;color:var(--rv-pale)'>Fruit shop</span> — Marta: Fui a fruteira aqui perto — also quitanda, frutaria, venda"],
    ["Hotel", "<span style='font-weight:800;color:var(--rv-pale)'>Hotel</span> — say oh-TEL with open O"],
    ["Livraria", "<span style='font-weight:800;color:var(--rv-pale)'>Bookstore</span> — livro is book, -aria is shop — Livraria sells livros"],
    ["Padaria", "<span style='font-weight:800;color:var(--rv-pale)'>Bakery</span> — pao place — Luiza brought quitutes da padaria — daily Brazil"],
    ["Papelaria", "<span style='font-weight:800;color:var(--rv-pale)'>Stationery shop</span> — papel is paper — not Papers office"],
    ["Posto de combustiveis", "<span style='font-weight:800;color:var(--rv-pale)'>Gas station</span> — posto for short — supermercado ali ao lado do posto"],
    ["Restaurante", "<span style='font-weight:800;color:var(--rv-pale)'>Restaurant</span> — Onde fica o restaurante — O restaurante fica perto da cafeteria"],
    ["Supermercado", "<span style='font-weight:800;color:var(--rv-pale)'>Supermarket</span> — Marta weekly shop — Pela manha vou ao supermercado"]
  ],
  "Lesson 3C - Where Adverbs": [
    ["aqui", "<span style='font-weight:800;color:var(--rv-pale)'>here — close to me</span> — Gigi esta aqui na sala — fruteira aqui perto means near our building"],
    ["ali", "<span style='font-weight:800;color:var(--rv-pale)'>there — middle distance</span> — supermercado ALI means not here but not far — between aqui and la"],
    ["la", "<span style='font-weight:800;color:var(--rv-pale)'>over there — far from me</span> — compras por LA means far market — Gigi esta la no jardim"],
    ["aqui perto", "<span style='font-weight:800;color:var(--rv-pale)'>near here</span> — Marta: fruteira aqui perto — building is the reference point"],
    ["ali ao lado", "<span style='font-weight:800;color:var(--rv-pale)'>right beside there</span> — supermercado ali ao lado do posto — ao lado is beside left or right"],
    ["atras", "<span style='font-weight:800;color:var(--rv-pale)'>behind</span> — Gigi esta atras do sofa"],
    ["dentro / fora", "<span style='font-weight:800;color:var(--rv-pale)'>inside / outside</span> — dentro da caixa vs fora da caixa — opposites together"],
    ["embaixo", "<span style='font-weight:800;color:var(--rv-pale)'>underneath</span> — embaixo da mesa — say eng-BUY-shoo — O celular esta em cima is opposite"],
    ["longe / perto", "<span style='font-weight:800;color:var(--rv-pale)'>far / near</span> — longe de Dona Ana vs perto de Dona Ana — Vou cedo porque ele fica LONGE"]
  ],
  "Lesson 3D - Days and Months": [
    ["domingo", "<span style='font-weight:800;color:var(--rv-pale)'>Sunday — masculine, use NO</span> — Domingo vou caminhar — Domingo costumo ficar em casa"],
    ["segunda-feira", "<span style='font-weight:800;color:var(--rv-pale)'>Monday — feminine, use NA</span> — Segunda vou ao medico — feira means fair, old market day"],
    ["terca-feira", "<span style='font-weight:800;color:var(--rv-pale)'>Tuesday — YOUR class day</span> — Tercas e quintas tenho ensaio — Terca ficarei na escola"],
    ["quarta-feira", "<span style='font-weight:800;color:var(--rv-pale)'>Wednesday</span> — Quarta vou ao futebol"],
    ["quinta-feira", "<span style='font-weight:800;color:var(--rv-pale)'>Thursday — Luiza routine day</span> — Hoje e quinta-feira, grupo de Historia — say KEEN-tah"],
    ["sexta-feira", "<span style='font-weight:800;color:var(--rv-pale)'>Friday</span> — Sexta sairei com amigos"],
    ["sabado", "<span style='font-weight:800;color:var(--rv-pale)'>Saturday — masculine, use NO</span> — Sabado vou ao cinema"],
    ["janeiro / fevereiro / marco", "<span style='font-weight:800;color:var(--rv-pale)'>Jan Feb Mar — all masculine</span> — Em janeiro ferias — As aulas comecam em marco"],
    ["abril / maio / junho", "<span style='font-weight:800;color:var(--rv-pale)'>Apr May Jun</span> — Em abril viajar — Maio Dia das Maes — Junho Dia dos Namorados"],
    ["julho / agosto / setembro", "<span style='font-weight:800;color:var(--rv-pale)'>Jul Aug Sep</span> — Julho ferias de inverno — Setembro primavera starts"],
    ["outubro / novembro / dezembro", "<span style='font-weight:800;color:var(--rv-pale)'>Oct Nov Dec</span> — Outubro Crianca — Novembro Republica — Dezembro Natal"],
    ["Hoje e quinta-feira", "<span style='font-weight:800;color:var(--rv-pale)'>Today is Thursday — time anchor</span> — Luiza to Leo — Hoje plus E plus day — your weekly pattern"]
  ],
  "Lesson 3E - Time Adverbs": [
    ["agora", "<span style='font-weight:800;color:var(--rv-pale)'>now</span>"],
    ["amanha", "<span style='font-weight:800;color:var(--rv-pale)'>tomorrow</span> — Amanha estaremos na escola — tilde makes nowng sound — do not mix with Pela manha morning"],
    ["Pela manha", "<span style='font-weight:800;color:var(--rv-pale)'>in the morning</span> — Pela manha vou ao supermercado — locution: two words act as one adverb"],
    ["cedo / tarde", "<span style='font-weight:800;color:var(--rv-pale)'>early / late</span> — Vou CEDO porque ele fica longe — opposites — say SEH-doo"],
    ["hoje / ontem", "<span style='font-weight:800;color:var(--rv-pale)'>today / yesterday</span> — Hoje e quinta-feira — say OH-jee with zh"],
    ["sempre / nunca", "<span style='font-weight:800;color:var(--rv-pale)'>always / never</span> — Sempre tomo banho — Nunca vou sem escovar — opposites"],
    ["geralmente / as vezes", "<span style='font-weight:800;color:var(--rv-pale)'>usually / sometimes</span> — Geralmente leio — As vezes ir ao cinema — frequency pair"],
    ["antes / atualmente / de repente", "<span style='font-weight:800;color:var(--rv-pale)'>before / currently / suddenly</span> — De repente ja estou com sono — suddenly sleepy"]
  ],
  "Lesson 3F - Daily Routine": [
    ["Eu acordo", "<span style='font-weight:800;color:var(--rv-pale)'>I wake up — acordar</span> — acordo bem cedo — say ah-KOR-doo"],
    ["Tomo cafe da manha", "<span style='font-weight:800;color:var(--rv-pale)'>I have breakfast — tomar</span> — tomar is take: take coffee, take shower — Tomo meu cafe"],
    ["Escovo os dentes", "<span style='font-weight:800;color:var(--rv-pale)'>I brush my teeth — escovar</span> — Nunca vou sem escovar os dentes"],
    ["Faco meu trabalho", "<span style='font-weight:800;color:var(--rv-pale)'>I do my work — fazer</span> — faco with C cedilla sound: FAH-soo — irregular EU form"],
    ["Vou para a escola", "<span style='font-weight:800;color:var(--rv-pale)'>I go to school — ir</span> — vou is I-go, irregular — Vou cedo, Vou para cama"],
    ["Eu estudo", "<span style='font-weight:800;color:var(--rv-pale)'>I study — estudar</span> — la estudo ate tarde — regular AR verb"],
    ["Eu almoco / Eu janto", "<span style='font-weight:800;color:var(--rv-pale)'>I have lunch / I have dinner</span> — almocar lunch, jantar dinner — Janto com familia"],
    ["Eu leio", "<span style='font-weight:800;color:var(--rv-pale)'>I read — ler</span> — Geralmente leio meu livro — irregular: leio not leo"],
    ["Tomo banho", "<span style='font-weight:800;color:var(--rv-pale)'>I shower — take bath</span> — Sempre tomo banho — same TOMAR as breakfast"],
    ["Assisto TV", "<span style='font-weight:800;color:var(--rv-pale)'>I watch TV — assistir</span> — Assisto TV na sala — drop EU naturally"],
    ["Eu durmo", "<span style='font-weight:800;color:var(--rv-pale)'>I sleep — dormir</span> — E hora de dormir — O to U change: durmo"],
    ["Todos os dias acordo cedo", "<span style='font-weight:800;color:var(--rv-pale)'>Every day I wake early — Mateus story</span> — de segunda a sexta routine — use EU verbs to tell YOUR day"]
  ],
  "Lesson 4A - Meios de Transporte": [
    ["o ônibus", "<span style='font-weight:800;color:var(--rv-pale)'>the bus — masculine public transport</span> — say OH-nee-boos — linha 165 ou 167 — Dona Ana vai de ônibus", "🚌"],
    ["o táxi", "<span style='font-weight:800;color:var(--rv-pale)'>the taxi — masculine individual transport</span> — say TAHK-see — cobra tarifa por distância e tempo — Se ficar tarde volte de táxi", "🚕"],
    ["a bicicleta", "<span style='font-weight:800;color:var(--rv-pale)'>the bicycle — feminine alternative transport</span> — say bee-see-KLEH-tah — Marta Paula e Antônio vão de bicicleta — controla gases e petróleo", "🚲"],
    ["o carro", "<span style='font-weight:800;color:var(--rv-pale)'>the car — masculine</span> — say KAH-hoo — Eles passam por toda a cidade de carro", "🚗"],
    ["o avião", "<span style='font-weight:800;color:var(--rv-pale)'>the airplane — masculine public for long distances</span> — say ah-vee-OWNG — locomoção aérea para longas distâncias", "✈️"],
    ["o barco", "<span style='font-weight:800;color:var(--rv-pale)'>the boat — masculine water transport</span> — say BAR-koo — barcos e balsas onde não há estrada", "🚢"],
    ["o caminhão", "<span style='font-weight:800;color:var(--rv-pale)'>the truck — masculine cargo transport</span> — say kah-meen-YOWNG — estradas levam cargas e passageiros", "🚚"],
    ["a caminhonete", "<span style='font-weight:800;color:var(--rv-pale)'>the pickup — feminine</span> — say kah-mee-oh-NEH-chee — menor que caminhão", "🛻"],
    ["o metrô", "<span style='font-weight:800;color:var(--rv-pale)'>the subway — masculine public transport</span> — say meh-TROH — esteja no ponto na estação de metrô na hora", "🚇"],
    ["a motocicleta", "<span style='font-weight:800;color:var(--rv-pale)'>the motorcycle — feminine</span> — say moh-toh-see-KLEH-tah — de moto no trânsito intenso", "🏍️"],
    ["o trem", "<span style='font-weight:800;color:var(--rv-pale)'>the train — masculine public transport</span> — say treng — van ônibus trem metrô e avião são públicos", "🚂"],
    ["a van", "<span style='font-weight:800;color:var(--rv-pale)'>the van — feminine public transport</span> — say vahng — Tu vais à escola de van", "🚐"],
    ["público vs individual", "<span style='font-weight:800;color:var(--rv-pale)'>Public vs individual transport</span> — van ônibus trem metrô avião: todos usam — táxi: individual com tarifa — biggest Aula 04 distinction", "🎫"]
  ],
  "Lesson 4B - Pegando o Ônibus": [
    ["Qual ônibus eu pego?", "<span style='font-weight:800;color:var(--rv-pale)'>Which bus do I take? — THE bus question</span> — Dona Ana to Tânia — pego is I-take from pegar — say PEH-goo", "🚌"],
    ["A linha 165 ou 167", "<span style='font-weight:800;color:var(--rv-pale)'>Bus line 165 or 167 — answer model</span> — Acho que a linha 165 ou 167 não tenho certeza — sempre confirme com o motorista", "🔢"],
    ["Aonde a senhora vai?", "<span style='font-weight:800;color:var(--rv-pale)'>Where are you going? — formal with movement</span> — Tânia to Dona Ana — Aonde adds TO — A senhora is formal you", "📍"],
    ["Vou visitar uma amiga adoentada", "<span style='font-weight:800;color:var(--rv-pale)'>I am going to visit a sick friend</span> — Dona Ana reason — vou is I-go — amiga adoentada que me ligou", "🏠"],
    ["A linha 167 passa aqui na rua?", "<span style='font-weight:800;color:var(--rv-pale)'>Does line 167 pass on this street? — itinerary question</span> — passa is it-passes — say PAH-sah", "🛣️"],
    ["Passa na rua de trás!", "<span style='font-weight:800;color:var(--rv-pale)'>It passes on the back street! — itinerary answer</span> — Não passa aqui passa LÁ — rua de trás is behind street", "↩️"],
    ["Vá até a esquina da padaria", "<span style='font-weight:800;color:var(--rv-pale)'>Go to the bakery corner — direction 1</span> — A senhora tem que ir até a esquina — até is up-to", "🥖"],
    ["Dobre à direita", "<span style='font-weight:800;color:var(--rv-pale)'>Turn right — direction 2</span> — say DOH-bree ah dee-RAY-tah — Siga uma quadra para a parada", "➡️"],
    ["A parada do ônibus", "<span style='font-weight:800;color:var(--rv-pale)'>The bus stop — destination</span> — Siga uma quadra para chegar à parada — parada is stop", "🚏"],
    ["O Largo do Mercado", "<span style='font-weight:800;color:var(--rv-pale)'>Market Square — Dona Ana destination</span> — ir até o Largo do Mercado — say LAR-goo", "🏪"],
    ["Volte antes de anoitecer!", "<span style='font-weight:800;color:var(--rv-pale)'>Come back before dark! — Tânia warning</span> — tenha cuidado viu Dona Ana — volte is come-back", "🌙"],
    ["Se ficar tarde, volte de táxi", "<span style='font-weight:800;color:var(--rv-pale)'>If it gets late, come back by taxi — safety plan</span> — Vou deixar meu telefone na sua bolsa — Qualquer coisa me liga", "🚕"]
  ],
  "Lesson 4C - Verbo Ir": [
    ["Eu vou", "<span style='font-weight:800;color:var(--rv-pale)'>I go — vou</span> — Vou visitar uma amiga — Vou tomar nota — say voh — irregular must-master", "➡️"],
    ["Tu vais", "<span style='font-weight:800;color:var(--rv-pale)'>You go — vais tu form</span> — Tu vais à escola de van — regional south and northeast", "➡️"],
    ["Ele vai / Ela vai", "<span style='font-weight:800;color:var(--rv-pale)'>He goes / She goes — vai</span> — Ele vai ao escritório de bicicleta — Aonde a senhora vai uses vai", "➡️"],
    ["Nós vamos", "<span style='font-weight:800;color:var(--rv-pale)'>We go — vamos</span> — Nós vamos ao restaurante de táxi — Vamos à praia short form", "➡️"],
    ["Eles vão", "<span style='font-weight:800;color:var(--rv-pale)'>They go — vão nasal</span> — Eles vão à praia — say vowng with tilde — hat marks plural", "➡️"],
    ["Eu vou ao supermercado", "<span style='font-weight:800;color:var(--rv-pale)'>I go to the supermarket — ao for masculine place</span> — quem vai vai A algum lugar — ao is a plus o", "🛒"],
    ["Tu vais à escola de van", "<span style='font-weight:800;color:var(--rv-pale)'>You go to school by van — à for feminine place</span> — à is a plus a — Vais à escola", "🚐"],
    ["Ele vai ao escritório de bicicleta", "<span style='font-weight:800;color:var(--rv-pale)'>He goes to the office by bike — transport with DE</span> — ir DE bicicleta DE táxi DE van — DE means by", "🚲"],
    ["Nós vamos ao restaurante de táxi", "<span style='font-weight:800;color:var(--rv-pale)'>We go to the restaurant by taxi</span> — ao restaurante masculine — de táxi is by-taxi", "🚕"],
    ["Eles vão à praia", "<span style='font-weight:800;color:var(--rv-pale)'>They go to the beach — à praia feminine</span> — Vamos à praia Vamos à escola — feminine places take À", "🏖️"],
    ["Aonde a senhora vai?", "<span style='font-weight:800;color:var(--rv-pale)'>Where are you going? — ir shows deslocamento</span> — o verbo ir indica deslocamento — movement TO somewhere", "📍"],
    ["Quem vai, vai a algum lugar", "<span style='font-weight:800;color:var(--rv-pale)'>Whoever goes, goes TO a place — golden rule</span> — masculine AO feminine À — Vai ao escritório Vou ao supermercado", "💡"]
  ],
  "Lesson 4D - Verbo Passar": [
    ["Eu passo", "<span style='font-weight:800;color:var(--rv-pale)'>I pass — passo</span> — Eu passo em frente à parada todo dia — say PAH-soo", "🛣️"],
    ["Tu passas", "<span style='font-weight:800;color:var(--rv-pale)'>You pass — passas tu form</span> — Tu passas pela padaria quando vens aqui — adds S for tu", "🛣️"],
    ["Ele passa", "<span style='font-weight:800;color:var(--rv-pale)'>He passes / It passes — passa</span> — Ele passa pelo Condomínio Brasil? — bus ele passa ali na parada", "🛣️"],
    ["Nós passamos", "<span style='font-weight:800;color:var(--rv-pale)'>We pass — passamos</span> — Nós passamos de bicicleta por você todas as manhãs — MOS for we", "🛣️"],
    ["Eles passam", "<span style='font-weight:800;color:var(--rv-pale)'>They pass — passam</span> — Eles passam por toda a cidade de carro — AM for they", "🛣️"],
    ["Eu passo em frente à parada", "<span style='font-weight:800;color:var(--rv-pale)'>I pass in front of the stop every day</span> — em frente à parada de ônibus todo dia — route past a point", "🚏"],
    ["Tu passas pela padaria", "<span style='font-weight:800;color:var(--rv-pale)'>You pass by the bakery — pela for feminine</span> — quando vens aqui em casa — pela is por plus a", "🥖"],
    ["Ele passa pelo Condomínio?", "<span style='font-weight:800;color:var(--rv-pale)'>Does it pass by the condo? — pelo for masculine</span> — pelo is por plus o — itinerary check", "🏠"],
    ["Nós passamos de bicicleta", "<span style='font-weight:800;color:var(--rv-pale)'>We pass by bike every morning</span> — por você todas as manhãs — DE tells transport PASSAR with DE too", "🚲"],
    ["Quem passa, passa por", "<span style='font-weight:800;color:var(--rv-pale)'>Whoever passes, passes BY something — golden rule</span> — por algum lugar ou alguém — pelo pela pelos pelas", "💡"],
    ["Ir é deslocamento, passar é percurso", "<span style='font-weight:800;color:var(--rv-pale)'>Ir is movement, passar is route — core distinction</span> — Aonde vai vs Por onde passa — exam trap of Aula 04", "🧭"]
  ],
  "Lesson 4E - Que Horas São": [
    ["Que horas são?", "<span style='font-weight:800;color:var(--rv-pale)'>What time is it? — THE time question</span> — say kee OH-rahs sowng — always plural SÃO except 1 oclock", "⏰"],
    ["São nove horas", "<span style='font-weight:800;color:var(--rv-pale)'>It is nine oclock — plural SÃO</span> — verbo ser for time — São nove São dez São quinze", "CLOCK|9|0"],
    ["São nove em ponto", "<span style='font-weight:800;color:var(--rv-pale)'>It is nine sharp — em ponto</span> — exactly on the hour — say eng POHN-too", "CLOCK|9|0"],
    ["São nove e quinze", "<span style='font-weight:800;color:var(--rv-pale)'>It is nine fifteen — e plus minutes</span> — São nove horas e quinze minutos — first half of clock", "CLOCK|9|15"],
    ["São nove e trinta", "<span style='font-weight:800;color:var(--rv-pale)'>It is nine thirty — 24h keeps trinta</span> — quinze horas e trinta after midday — 15h30 is quinze e trinta not meia", "CLOCK|9|30"],
    ["São nove e meia", "<span style='font-weight:800;color:var(--rv-pale)'>It is half past nine — meia for 30 in 12h</span> — 9h30 is nove e meia — Mas atenção 15h30 stays trinta minutos", "CLOCK|9|30"],
    ["São nove e quarenta", "<span style='font-weight:800;color:var(--rv-pale)'>It is nine forty — past 30 counts up</span> — Quatro e quarenta Onze e quarenta e cinco — digital style", "CLOCK|9|40"],
    ["São vinte para as dez", "<span style='font-weight:800;color:var(--rv-pale)'>It is twenty to ten — PARA after 30</span> — após trinta informamos o que FALTA — Vinte para as cinco", "CLOCK|9|40"],
    ["Faltam vinte para as dez", "<span style='font-weight:800;color:var(--rv-pale)'>Twenty minutes are missing to ten — FALTAM form</span> — same as São vinte para — faltam is they-lack", "CLOCK|9|40"],
    ["É uma hora", "<span style='font-weight:800;color:var(--rv-pale)'>It is one oclock — singular É</span> — É uma hora da manhã da tarde da madrugada — only 1 uses É", "CLOCK|1|0"],
    ["É meio-dia", "<span style='font-weight:800;color:var(--rv-pale)'>It is noon — singular É</span> — say MAY-oo DEE-ah — 12:00 Meio dia — sun icon", "CLOCK|12|0"],
    ["É meia-noite", "<span style='font-weight:800;color:var(--rv-pale)'>It is midnight — singular É</span> — say MAY-ah NOY-chee — 00:00 Meia noite — moon icon", "CLOCK|0|0"]
  ],
  "Lesson 4F - Relógio 12h e 24h": [
    ["Três horas da manhã", "<span style='font-weight:800;color:var(--rv-pale)'>3 AM — 12h model with expression</span> — 03:00 Três horas da manhã — numeral plus da manhã", "CLOCK|3|0"],
    ["Três horas da tarde", "<span style='font-weight:800;color:var(--rv-pale)'>3 PM — same clock different period</span> — modelo 12h usa da manhã tarde noite — 12h needs expression", "CLOCK|3|0"],
    ["Seis horas da manhã", "<span style='font-weight:800;color:var(--rv-pale)'>6 AM — morning bus time</span> — 06:00 Seis horas da manhã — Tânia: às 13 e 30 tem um bus", "CLOCK|6|0"],
    ["Seis horas da tarde", "<span style='font-weight:800;color:var(--rv-pale)'>6 PM — evening</span> — 18:00 dezoito horas in 24h — 12h says seis da tarde 24h says dezoito", "CLOCK|6|0"],
    ["03:00 três horas / 15:00 quinze horas", "<span style='font-weight:800;color:var(--rv-pale)'>3 AM vs 3 PM in 24h — only numerals</span> — modelo 24h usa só numerais — 03 Três 15 Quinze", "CLOCK|3|0"],
    ["06:00 seis horas / 18:00 dezoito horas", "<span style='font-weight:800;color:var(--rv-pale)'>6 AM vs 6 PM in 24h</span> — 06 seis 18 dezoito — transporte público usa 24h", "CLOCK|6|0"],
    ["00:00 meia-noite / 12:00 meio-dia", "<span style='font-weight:800;color:var(--rv-pale)'>Midnight vs noon in 24h</span> — 00 Meia noite 12 Meio dia — É singular for both", "CLOCK|12|0"],
    ["Nove e dez", "<span style='font-weight:800;color:var(--rv-pale)'>9:10 — minutes past the hour</span> — Nove horas e dez minutos — relógio digital style", "CLOCK|9|10"],
    ["Onze e quarenta e cinco", "<span style='font-weight:800;color:var(--rv-pale)'>11:45 — late minutes still E</span> — Onze horas e quarenta e cinco minutos — then switch to PARA", "CLOCK|11|45"],
    ["Cinco para o meio-dia", "<span style='font-weight:800;color:var(--rv-pale)'>Five to noon — PARA o singular</span> — 11:55 Cinco minutos para o meio dia — meio-dia takes O", "CLOCK|11|55"],
    ["Dez para a uma da tarde", "<span style='font-weight:800;color:var(--rv-pale)'>Ten to one PM — PARA A singular</span> — 12:50 Dez minutos para a uma hora da tarde — uma takes A", "CLOCK|12|50"],
    ["Vinte para as cinco da tarde", "<span style='font-weight:800;color:var(--rv-pale)'>Twenty to five PM — PARA AS plural</span> — 16:40 Vinte minutos para as cinco horas da tarde — plural takes AS", "CLOCK|4|40"]
  ]
};

window.APP_GROUPS = {
  "Lesson 1 - Bem-vindo ao Condominio Brasil!": {
    subtitle: "Greetings, ser, alphabet, nouns, numbers",
    emoji: "🏠",
    parts: ["Lesson 1A - Greetings and Farewells", "Lesson 1B - Courtesy Expressions", "Lesson 1C - Ser and Pronouns", "Lesson 1D - Alphabet A to Z", "Lesson 1E - Nouns Gender and Number", "Lesson 1F - Nationalities", "Lesson 1G - Numbers 0 to 100", "Lesson 1H - Estar and Feelings"]
  },
  "Lesson 2 - Fazendo Amigos": {
    subtitle: "Questions, ter, morar, help phrases",
    emoji: "👥",
    parts: ["Lesson 2A - Question Words", "Lesson 2B - Formal and Informal You", "Lesson 2C - Possessives", "Lesson 2D - Verb Ter To Have", "Lesson 2E - Verb Morar To Live", "Lesson 2F - Asking for Help"]
  },
  "Lesson 3 - Onde Fica o Mercado?": {
    subtitle: "Places, days, routine",
    emoji: "🗺️",
    parts: ["Lesson 3A - Ficar vs Estar", "Lesson 3B - Shops and Places", "Lesson 3C - Where Adverbs", "Lesson 3D - Days and Months", "Lesson 3E - Time Adverbs", "Lesson 3F - Daily Routine"]
  },
  "Lesson 4 - Vamos de Ônibus ou a Pé?": {
    subtitle: "Transport, ir and passar, telling time",
    emoji: "🚌",
    parts: ["Lesson 4A - Meios de Transporte", "Lesson 4B - Pegando o Ônibus", "Lesson 4C - Verbo Ir", "Lesson 4D - Verbo Passar", "Lesson 4E - Que Horas São", "Lesson 4F - Relógio 12h e 24h"]
  }
};

window.APP_DIALOGS = {
  "Lesson 1 - Bem-vindo ao Condominio Brasil!": [
    { title: "Marta meets Leo", lines: [["Marta", "Bom dia! Você é o porteiro?", "Good morning! Are you the doorman?"], ["Leo", "Meu nome é Leo, sou o síndico. Muito prazer. Seja bem-vinda!", "My name is Leo, I am the manager. Nice to meet you. Welcome!"], ["Marta", "Sou a nova moradora do 702, Marta Reis.", "I am the new resident of 702, Marta Reis."], ["Marta", "Está bem, muito obrigada. Até logo!", "All right, thank you very much. See you later!"]] },
    { title: "Marta and Rudinei", lines: [["Marta", "Olá, boa tarde! Sou a Marta, do 702.", "Hi, good afternoon! I am Marta, from 702."], ["Rudinei", "Muito prazer! Sou Rudinei, o porteiro.", "Nice to meet you! I am Rudinei, the doorman."]] },
    { title: "Spelling on the phone", lines: [["Marta", "É Marta. M-A-R-T-A.", "It is Marta. M-A-R-T-A."], ["Telefonista", "Seu nome é Marta Reis, M-A-R-T-A R-E-I-S.", "Your name is Marta Reis..."], ["Marta", "Rua dos Presidentes, número oitenta e nove.", "Presidents Street, number eighty-nine."]] },
    { title: "Leo and Rasmus", lines: [["Leo", "De onde você é?", "Where are you from?"], ["Rasmus", "Sou brasileiro, mas meus pais vieram da Suécia.", "I am Brazilian, but my parents came from Sweden."], ["Leo", "Quantos anos você tem?", "How old are you?"], ["Rasmus", "Tenho quarenta e três anos.", "I am 43 years old."]] }
  ],
  "Lesson 2 - Fazendo Amigos": [
    { title: "Luiza welcomes Marta", lines: [["Luiza", "Ola! Tudo bem? Voce e a Marta?", "Hi! All good? Are you Marta?"], ["Luiza", "Me chamo Luiza. Sou filha do Leo.", "I am called Luiza. I am Leo's daughter."], ["Luiza", "Onde posso deixar a cesta?", "Where can I leave the basket?"], ["Marta", "Quantos anos voce tem?", "How old are you?"], ["Luiza", "Tenho 14 anos!", "I am 14!"]] },
    { title: "Rudinei and Dona Ana", lines: [["Rudinei", "O que e isso, dona Ana?", "What is this, Mrs Ana?"], ["Dona Ana", "E um relogio de bolso. Veio da Franca.", "It is a pocket watch. It came from France."], ["Rudinei", "A senhora quer que eu fale com ele?", "Would you like me to talk to him?"]] },
    { title: "Where do you live?", lines: [["Leo", "Onde voce mora?", "Where do you live?"], ["Rasmus", "Moro na Rua dos Presidentes.", "I live on Presidents Street."], ["Leo", "Onde voces moram?", "Where do you all live?"], ["Amigos", "Nos moramos no Condominio Brasil.", "We live in Condominium Brasil."]] }
  ],
  "Lesson 3 - Onde Fica o Mercado?": [
    { title: "In the elevator", lines: [["Leo", "E voce? Andou fazendo compras?", "And you? Been shopping?"], ["Marta", "Fui a fruteira aqui perto e ao supermercado ali ao lado do posto.", "I went to the fruit shop near here and the supermarket beside the gas station."], ["Marta", "E onde fica esse mercadinho?", "And where is that little market?"], ["Leo", "Ele fica bem na esquina com a avenida.", "It is right on the corner with the avenue."]] },
    { title: "Thursday routine", lines: [["Leo", "Oi, filha! Onde voce estava?", "Hi, daughter! Where were you?"], ["Luiza", "Oi, pai! Hoje e quinta-feira. Eu estava no grupo de Historia.", "Hi, dad! Today is Thursday. I was in the History group."]] },
    { title: "Mateus day", lines: [["Mateus", "Todos os dias acordo bem cedo e tomo meu cafe da manha.", "Every day I wake up very early and have breakfast."], ["Mateus", "Pela manha vou ao supermercado. Vou cedo porque ele fica longe.", "In the morning I go to the supermarket. I go early because it is far."], ["Mateus", "A noite tomo banho, janto e durmo.", "At night I shower, have dinner and sleep."]] }
  ],
  "Lesson 4 - Vamos de Ônibus ou a Pé?": [
    { title: "Dona Ana e Tânia — qual ônibus?", lines: [["Dona Ana", "Tânia, você sabe qual ônibus eu pego para ir até o Largo do Mercado?", "Tânia, do you know which bus I take to go to Market Square?"], ["Tânia", "Acho que a linha 165 ou 167, não tenho certeza. É bom a senhora perguntar ao motorista.", "I think line 165 or 167, not sure. Better ask the driver to confirm."], ["Dona Ana", "E a linha 167 passa aqui na rua?", "And does line 167 pass on this street?"], ["Tânia", "Não. Passa na rua de trás! Vá até a esquina da padaria e dobre à direita.", "No. It passes on the back street! Go to the bakery corner and turn right."], ["Tânia", "Siga uma quadra para chegar à parada do ônibus.", "Go one block to reach the bus stop."], ["Dona Ana", "E quais os horários que ele passa ali na parada?", "And what times does it pass at the stop?"], ["Tânia", "Às 13 horas e 30 tem um. Depois só às 15 horas. Se ficar tarde, volte de táxi!", "At 1:30pm there is one. Then only at 3pm. If it gets late, come back by taxi!"]] },
    { title: "Marta, Antônio e Paula — bicicleta", lines: [["Marta", "Minha nossa! Que falta de respeito!", "Oh my! How disrespectful!"], ["Paula", "Nossa! Que perigo!", "Wow! How dangerous!"], ["Antônio", "Não é fácil! Nós, ciclistas, sabemos como é essa lei do mais forte no trânsito.", "It is not easy! We cyclists know this law of the strongest in traffic."], ["Marta", "Vocês costumam ir de bicicleta para todos os lugares?", "Do you usually go by bike everywhere?"], ["Paula", "O tempo todo. Para trabalhar, para passear.", "All the time. To work, to hang out."], ["Antônio", "Você deve estar sempre atento. Não pode descuidar um segundo.", "You must always stay alert. Cannot relax one second."]] },
    { title: "A linha 167 passa aqui?", lines: [["Tânia", "Aonde a senhora vai?", "Where are you going?"], ["Dona Ana", "Vou visitar uma velha amiga adoentada.", "I am going to visit a sick old friend."], ["Tânia", "A senhora tem que ir até a esquina e dobrar à direita.", "You have to go to the corner and turn right."], ["Dona Ana", "Vou tomar nota para não esquecer.", "I will take notes so I do not forget."]] }
  ]
};
