const database = {
  "Brazilian Portuguese Alphabet": [
    ["A","<span style='font-weight:800;color:var(--rv-pale)'>á [a]</span> — 'ah' as in father — Avião (airplane)"],
    ["B","<span style='font-weight:800;color:var(--rv-pale)'>bê [be]</span> — 'beh' as in boy — Bola (ball)"],
    ["C","<span style='font-weight:800;color:var(--rv-pale)'>cê [se]</span> — 'seh' — Casa (house)"],
    ["D","<span style='font-weight:800;color:var(--rv-pale)'>dê [de]</span> — 'deh' — Dado (dice)"],
    ["E","<span style='font-weight:800;color:var(--rv-pale)'>é [ɛ/e]</span> — 'eh' — Escola (school)"],
    ["F","<span style='font-weight:800;color:var(--rv-pale)'>efe [ɛfi]</span> — 'eh-fee' — Faca (knife)"],
    ["G","<span style='font-weight:800;color:var(--rv-pale)'>gê [ʒe]</span> — 'zheh' — Gato (cat)"],
    ["H","<span style='font-weight:800;color:var(--rv-pale)'>agá [a'ga]</span> — silent — Hotel (hotel)"],
    ["I","<span style='font-weight:800;color:var(--rv-pale)'>i [i]</span> — 'ee' as in see — Igreja (church)"],
    ["J","<span style='font-weight:800;color:var(--rv-pale)'>jota [ʒɔta]</span> — 'zhota' — Janela (window)"],
    ["K","<span style='font-weight:800;color:var(--rv-pale)'>cá [ka]</span> — 'kah' — Kiwi (kiwi)"],
    ["L","<span style='font-weight:800;color:var(--rv-pale)'>ele [ɛli]</span> — 'eh-lee' — Lua (moon)"],
    ["M","<span style='font-weight:800;color:var(--rv-pale)'>eme [ẽmi]</span> — 'em-ee' — Mesa (table)"],
    ["N","<span style='font-weight:800;color:var(--rv-pale)'>ene [ẽni]</span> — 'en-ee' — Navio (ship)"],
    ["O","<span style='font-weight:800;color:var(--rv-pale)'>ó [ɔ/o]</span> — 'aw/oh' — Ovo (egg)"],
    ["P","<span style='font-weight:800;color:var(--rv-pale)'>pê [pe]</span> — 'peh' — Pato (duck)"],
    ["Q","<span style='font-weight:800;color:var(--rv-pale)'>quê [ke]</span> — 'keh' — Queijo (cheese)"],
    ["R","<span style='font-weight:800;color:var(--rv-pale)'>erre [ɛʁi]</span> — 'eh-hee' (guttural R) — Rato (rat)"],
    ["S","<span style='font-weight:800;color:var(--rv-pale)'>esse [ɛsi]</span> — 'eh-see' — Sol (sun)"],
    ["T","<span style='font-weight:800;color:var(--rv-pale)'>tê [te]</span> — 'teh' — Teto (ceiling)"],
    ["U","<span style='font-weight:800;color:var(--rv-pale)'>u [u]</span> — 'oo' — Uva (grape)"],
    ["V","<span style='font-weight:800;color:var(--rv-pale)'>vê [ve]</span> — 'veh' — Vaca (cow)"],
    ["W","<span style='font-weight:800;color:var(--rv-pale)'>dáblio [dablju]</span> — 'dah-blee-oo' — Website"],
    ["X","<span style='font-weight:800;color:var(--rv-pale)'>xis [ʃis]</span> — 'shees' — Xícara (cup)"],
    ["Y","<span style='font-weight:800;color:var(--rv-pale)'>ípsilon [ipsilõ]</span> — 'ee-psee-lon' — Yoga"],
    ["Z","<span style='font-weight:800;color:var(--rv-pale)'>zê [ze]</span> — 'zeh' — Zebra (zebra)"]
  ],
  "Communicating & Essentials": [
    // Topic 1: Communicating — Greetings & Farewells (13)
    ["Bom dia!","<span style='font-weight:800;color:var(--rv-pale)'>Good morning!</span> — Formal Greeting — use 6am–12pm, most common morning hello"],
    ["Boa tarde!","<span style='font-weight:800;color:var(--rv-pale)'>Good afternoon!</span> — Formal Greeting — 12pm–6pm"],
    ["Boa noite!","<span style='font-weight:800;color:var(--rv-pale)'>Good evening! / Good night!</span> — Formal Greeting — after 6pm (hello & goodbye)"],
    ["Oi!","<span style='font-weight:800;color:var(--rv-pale)'>Hi!</span> — Informal Greeting — friends & peers, very Brazilian"],
    ["Olá!","<span style='font-weight:800;color:var(--rv-pale)'>Hello!</span> — Neutral Greeting — safe in any situation"],
    ["Adeus!","<span style='font-weight:800;color:var(--rv-pale)'>Goodbye!</span> — Formal Farewell — final, less common daily; prefer Tchau/Até logo"],
    ["Tchau!","<span style='font-weight:800;color:var(--rv-pale)'>Bye!</span> — Informal Farewell — #1 in Brazil, casual"],
    ["Até logo!","<span style='font-weight:800;color:var(--rv-pale)'>See you later!</span> — Informal Farewell — see you soon"],
    ["Até mais!","<span style='font-weight:800;color:var(--rv-pale)'>See you! / See you later!</span> — Informal Farewell — casual, very common"],
    ["Muito prazer!","<span style='font-weight:800;color:var(--rv-pale)'>Nice to meet you!</span> — Polite, no gender change — after introductions"],
    ["Desculpa!","<span style='font-weight:800;color:var(--rv-pale)'>Sorry!</span> — Informal — formal is Desculpe! / Com licença..."],
    ["Bem-vinda!","<span style='font-weight:800;color:var(--rv-pale)'>Welcome! (to a woman)</span> — Polite gendered — to a man → Bem-vindo! (T2)"],
    ["Muito obrigada!","<span style='font-weight:800;color:var(--rv-pale)'>Thank you very much! (said by a woman)</span> — Gendered — man says Muito obrigado!"],
    // Topic 2: Polite Expressions — Gendered (6) + Neutral (4)
    ["Bem-vindo!","<span style='font-weight:800;color:var(--rv-pale)'>Welcome! (to a man)</span> — Polite gendered — ends -o = man"],
    ["Obrigado!","<span style='font-weight:800;color:var(--rv-pale)'>Thank you! (said by a man)</span> — Gendered — -o speaker = man"],
    ["Obrigada!","<span style='font-weight:800;color:var(--rv-pale)'>Thank you! (said by a woman)</span> — Gendered — -a speaker = woman"],
    ["Muito obrigado!","<span style='font-weight:800;color:var(--rv-pale)'>Thank you very much! (said by a man)</span> — Gendered — ends -o"],
    ["Prazer em conhecê-lo!","<span style='font-weight:800;color:var(--rv-pale)'>Nice to meet you! (to a man)</span> — Gendered — -lo = him"],
    ["Prazer em conhecê-la!","<span style='font-weight:800;color:var(--rv-pale)'>Nice to meet you! (to a woman)</span> — Gendered — -la = her"],
    ["Por favor...","<span style='font-weight:800;color:var(--rv-pale)'>Please...</span> — Polite, no gender change — universal"],
    ["Por gentileza...","<span style='font-weight:800;color:var(--rv-pale)'>Please... / Kindly...</span> — No gender change — more formal than Por favor"],
    ["Com licença...","<span style='font-weight:800;color:var(--rv-pale)'>Excuse me...</span> — No gender change — to pass or get attention"],
    // Topic 3: Personal Pronouns — Singular (4) + Plural (4) — corrected orthography
    ["Eu","<span style='font-weight:800;color:var(--rv-pale)'>I</span> — Singular — 1st person"],
    ["Você","<span style='font-weight:800;color:var(--rv-pale)'>You</span> — Singular — #1 in Brazil (Tu is regional south/northeast)"],
    ["Ela","<span style='font-weight:800;color:var(--rv-pale)'>She</span> — Singular Feminine — 3rd person"],
    ["Ele","<span style='font-weight:800;color:var(--rv-pale)'>He</span> — Singular Masculine — 3rd person (completes set for Ser)"],
    ["Nós","<span style='font-weight:800;color:var(--rv-pale)'>We</span> — Plural — 1st person"],
    ["Vocês","<span style='font-weight:800;color:var(--rv-pale)'>You (plural)</span> — 2nd Plural — you all"],
    ["Eles","<span style='font-weight:800;color:var(--rv-pale)'>They (masculine/mixed)</span> — Plural — 3rd person"],
    ["Elas","<span style='font-weight:800;color:var(--rv-pale)'>They (feminine)</span> — Plural — all women"],
    // Topic 4: Verb Ser — Present Tense (6) — with example sentences
    ["Eu sou","<span style='font-weight:800;color:var(--rv-pale)'>I am — sou</span> — Eu sou brasileiro. / Sou brasileiro. (I am Brazilian.)"],
    ["Tu és","<span style='font-weight:800;color:var(--rv-pale)'>You are — és</span> — Tu és estrangeira. / És estrangeira. (You are foreign.) — informal/regional"],
    ["Ele é / Ela é","<span style='font-weight:800;color:var(--rv-pale)'>He / She is — é</span> — Ela é estudante. / É estudante. (She is a student.)"],
    ["Nós somos","<span style='font-weight:800;color:var(--rv-pale)'>We are — somos</span> — Nós somos amigos. / Somos amigos. (We are friends.)"],
    ["Vós sois","<span style='font-weight:800;color:var(--rv-pale)'>You are — sois</span> — Vós sois competentes. / Sois competentes. (You are competent.) — very formal/archaic, rare in Brazil"],
    ["Eles são / Elas são","<span style='font-weight:800;color:var(--rv-pale)'>They are — são</span> — Eles são brasileiros. / São brasileiros. (They are Brazilian.)"]
  ],
  "Articles & Gender": [
    // Topic 1: Definite o/a/os/as (8) — conversational, minimal word[0] for TTS
    ["o","<span style='font-weight:800;color:var(--rv-pale)'>o [oo] — Definite Masculine Singular 'the'</span> — specific masculine noun — o livro (the book)"],
    ["a","<span style='font-weight:800;color:var(--rv-pale)'>a [ah] — Definite Feminine Singular 'the'</span> — specific feminine noun — a casa (the house)"],
    ["os","<span style='font-weight:800;color:var(--rv-pale)'>os [oosh] — Definite Masculine Plural 'the'</span> — add -s to o — os livros (the books)"],
    ["as","<span style='font-weight:800;color:var(--rv-pale)'>as [ash] — Definite Feminine Plural 'the'</span> — add -s to a — as casas (the houses)"],
    ["o livro","<span style='font-weight:800;color:var(--rv-pale)'>o livro — the book</span> — ends -o → Masculine — o/um"],
    ["a casa","<span style='font-weight:800;color:var(--rv-pale)'>a casa — the house</span> — ends -a → Feminine — a/uma"],
    ["o dia","<span style='font-weight:800;color:var(--rv-pale)'>o dia — the day</span> — Masculine despite -a — exception!"],
    ["a foto","<span style='font-weight:800;color:var(--rv-pale)'>a foto — the photo</span> — Shortened Feminine (fotografia) — keeps fem"],
    // Topic 2: Indefinite um/uma/uns/umas (8) — Brazilian daily + fixed
    ["um","<span style='font-weight:800;color:var(--rv-pale)'>um [ũ] — Indefinite Masculine Singular 'a/an'</span> — non-specific — um livro (a book)"],
    ["uma","<span style='font-weight:800;color:var(--rv-pale)'>uma [ˈũmɐ] — Indefinite Feminine Singular 'a/an'</span> — non-specific — uma casa (a house)"],
    ["uns","<span style='font-weight:800;color:var(--rv-pale)'>uns [ũs] — Indefinite Masculine Plural 'some'</span> — add -s to um — uns livros (some books)"],
    ["umas","<span style='font-weight:800;color:var(--rv-pale)'>umas [ˈũmɐs] — Indefinite Feminine Plural 'some'</span> — add -s to uma — umas casas (some houses)"],
    ["um pão","<span style='font-weight:800;color:var(--rv-pale)'>um pão — a bread</span> — Brazilian daily — pão francês"],
    ["uma coxinha","<span style='font-weight:800;color:var(--rv-pale)'>uma coxinha — a coxinha</span> — Brazilian daily — chicken croquette"],
    ["o lápis","<span style='font-weight:800;color:var(--rv-pale)'>o lápis — the pencil</span> — Fixed Masculine — never *a lápis, ends -is but masc"],
    ["a caneta","<span style='font-weight:800;color:var(--rv-pale)'>a caneta — the pen</span> — Fixed Feminine — never *o caneta"],
    // Topic 3: Variable/Common + Table (8) — conversational pairs
    ["o garoto","<span style='font-weight:800;color:var(--rv-pale)'>o garoto — the boy</span> — Variable Gender (biforme) — base form"],
    ["a garota","<span style='font-weight:800;color:var(--rv-pale)'>a garota — the girl</span> — Variable Gender — -o → -a change"],
    ["o aluno","<span style='font-weight:800;color:var(--rv-pale)'>o aluno — the male student</span> — Variable Gender — -o → -a"],
    ["a aluna","<span style='font-weight:800;color:var(--rv-pale)'>a aluna — the female student</span> — Variable Gender — same root"],
    ["o estudante","<span style='font-weight:800;color:var(--rv-pale)'>o estudante — the male student</span> — Common of Two Genders (uniform) — article shows gender"],
    ["a estudante","<span style='font-weight:800;color:var(--rv-pale)'>a estudante — the female student</span> — Common — noun unchanged, only article changes"],
    ["o porteiro","<span style='font-weight:800;color:var(--rv-pale)'>o porteiro — the doorman</span> — Table: Masculine Definite o (the) — specific person"],
    ["a síndica","<span style='font-weight:800;color:var(--rv-pale)'>a síndica — the property manager</span> — Table: Feminine Definite a (the) — specific person"]
  ],
  "Greetings & Politeness": [
    ["Olá / Oi", "Hello / Hi"],
    ["Bom dia", "Good morning"],
    ["Boa tarde", "Good afternoon"],
    ["Boa noite", "Good night / Good evening"],
    ["Por favor", "Please"],
    ["Obrigado / Obrigada", "Thank you (masc./fem.)"],
    ["Desculpe", "Sorry"],
    ["Com licença", "Excuse me"],
    ["De nada", "You're welcome"],
    ["Tudo bem?", "How are you? / Everything good?"],
    ["Até logo", "See you later"],
    ["Até amanhã", "See you tomorrow"],
    ["Bem-vindo", "Welcome"],
    ["Como vai?", "How's it going?"],
    ["Muito prazer", "Nice to meet you"],
    ["Igualmente", "Likewise"],
    ["Até mais", "Goodbye"]
  ],
  "Question Words": [
    ["Quem", "Who"],
    ["O que", "What"],
    ["Onde", "Where"],
    ["Quando", "When"],
    ["Por que", "Why"],
    ["Como", "How"]
  ],
  "Essential Verbs": [
    ["Ser", "To be (permanent, identity)"],
    ["Estar", "To be (temporary, state)"],
    ["Ter", "To have"],
    ["Ir", "To go"],
    ["Fazer", "To do / To make"],
    ["Poder", "Can / To be able to"],
    ["Dizer", "To say / To tell"],
    ["Ver", "To see"],
    ["Dar", "To give"],
    ["Saber", "To know (facts, how to do something)"],
    ["Vir", "To come"],
    ["Falar", "To speak/talk"],
    ["Ouvir", "To hear/listen"],
    ["Comer", "To eat"],
    ["Beber", "To drink"],
    ["Dormir", "To sleep"],
    ["Acordar", "To wake up"],
    ["Trabalhar", "To work"],
    ["Estudar", "To learn/study"],
    ["Aprender", "To learn"],
    ["Escrever", "To write"],
    ["Ler", "To read"],
    ["Correr", "To run"],
    ["Andar", "To walk"],
    ["Sentar", "To sit"],
    ["Levantar", "To stand up"],
    ["Abrir", "To open"],
    ["Fechar", "To close"],
    ["Comprar", "To buy"],
    ["Vender", "To sell"],
    ["Pagar", "To pay"],
    ["Ajudar", "To help"],
    ["Precisar", "To need"],
    ["Querer", "To want"],
    ["Pensar", "To think"],
    ["Sentir", "To feel"],
    ["Amar", "To love"],
    ["Gostar", "To like"],
    ["Brincar", "To play"],
    ["Cantar", "To sing"],
    ["Dançar", "To dance"],
    ["Cozinhar", "To cook"],
    ["Limpar", "To clean"],
    ["Lavar", "To wash"],
    ["Esperar", "To wait"],
    ["Chegar", "To arrive"],
    ["Sair", "To leave/go out"],
    ["Voltar", "To return"],
    ["Perguntar", "To ask"],
    ["Responder", "To answer"],
    ["Encontrar", "To find/meet"],
    ["Morar", "To live/reside"],
    ["Nadar", "To swim"]
  ],
  "Common Adjectives": [
    ["Bom / Boa", "Good (masc./fem.)"],
    ["Ruim", "Bad"],
    ["Grande", "Big/Large"],
    ["Pequeno / Pequena", "Small (masc./fem.)"],
    ["Novo / Nova", "New (masc./fem.)"],
    ["Alto", "Tall/High"],
    ["Baixo", "Short/Low"],
    ["Gordo", "Fat"],
    ["Magro", "Thin/Slim"],
    ["Bonito", "Beautiful/Pretty"],
    ["Feio", "Ugly"],
    ["Velho", "Old"],
    ["Rápido", "Fast"],
    ["Devagar", "Slow"],
    ["Forte", "Strong"],
    ["Fraco", "Weak"],
    ["Fácil", "Easy"],
    ["Difícil", "Difficult"],
    ["Feliz", "Happy"],
    ["Triste", "Sad"],
    ["Cansado", "Tired"],
    ["Animado", "Excited/Lively"],
    ["Bravo", "Angry"],
    ["Calmo", "Calm"],
    ["Quente", "Hot"],
    ["Frio", "Cold"],
    ["Mau/Ruim", "Bad"],
    ["Certo", "Right/Correct"],
    ["Errado", "Wrong"],
    ["Limpo", "Clean"],
    ["Sujo", "Dirty"],
    ["Cheio", "Full"],
    ["Vazio", "Empty"]
  ],
  "Basic Nouns": [
    ["Comida", "Food"],
    ["Água", "Water"],
    ["Casa", "House / Home"],
    ["Trabalho", "Work / Job"],
    ["Escola", "School"],
    ["Dinheiro", "Money"],
    ["Carro", "Car"],
    ["Amigo / Amiga", "Friend (masc./fem.)"],
    ["Cidade", "City"],
    ["Família", "Family"],
    ["Livro", "Book"],
    ["Cão / Cachorro", "Dog"],
    ["Gato", "Cat"],
    ["Dia", "Day"],
    ["Noite", "Night"]
  ],
  "Numbers": [
    ["Zero", "0"],
    ["Um/Uma", "1"],
    ["Dois/Duas", "2"],
    ["Três", "3"],
    ["Quatro", "4"],
    ["Cinco", "5"],
    ["Seis", "6"],
    ["Sete", "7"],
    ["Oito", "8"],
    ["Nove", "9"],
    ["Dez", "10"],
    ["Onze", "11"],
    ["Doze", "12"],
    ["Treze", "13"],
    ["Quatorze", "14"],
    ["Quinze", "15"],
    ["Dezesseis", "16"],
    ["Dezessete", "17"],
    ["Dezoito", "18"],
    ["Dezenove", "19"],
    ["Vinte", "20"],
    ["Trinta", "30"],
    ["Quarenta", "40"],
    ["Cinquenta", "50"],
    ["Sessenta", "60"],
    ["Setenta", "70"],
    ["Oitenta", "80"],
    ["Noventa", "90"],
    ["Cem", "100"],
    ["Mil", "1000"]
  ],
  "Days & Months": [
    ["Segunda-feira", "Monday"],
    ["Terça-feira", "Tuesday"],
    ["Quarta-feira", "Wednesday"],
    ["Quinta-feira", "Thursday"],
    ["Sexta-feira", "Friday"],
    ["Sábado", "Saturday"],
    ["Domingo", "Sunday"],
    ["Hoje", "Today"],
    ["Amanhã", "Tomorrow"],
    ["Ontem", "Yesterday"],
    ["Janeiro", "January"],
    ["Fevereiro", "February"],
    ["Março", "March"],
    ["Abril", "April"],
    ["Maio", "May"],
    ["Junho", "June"],
    ["Julho", "July"],
    ["Agosto", "August"],
    ["Setembro", "September"],
    ["Outubro", "October"],
    ["Novembro", "November"],
    ["Dezembro", "December"],
    ["Semana", "Week"],
    ["Mês", "Month"],
    ["Ano", "Year"],
    ["Hora", "Hour"],
    ["Minuto", "Minute"],
    ["Segundo", "Second"],
    ["Agora", "Now"]
  ],
  "Colors": [
    ["Vermelho", "Red"],
    ["Azul", "Blue"],
    ["Amarelo", "Yellow"],
    ["Verde", "Green"],
    ["Preto", "Black"],
    ["Branco", "White"],
    ["Laranja", "Orange"],
    ["Roxo", "Purple"],
    ["Rosa", "Pink"],
    ["Marrom", "Brown"],
    ["Cinza", "Gray"],
    ["Dourado", "Gold"],
    ["Prata", "Silver"],
    ["Bege", "Beige"],
    ["Turquesa", "Turquoise"],
    ["Lilás", "Lilac"],
    ["Vinho", "Burgundy"],
    ["Creme", "Cream"],
    ["Claro", "Light"],
    ["Escuro", "Dark"]
  ],
  "Family Members": [
    ["Mãe", "Mother"],
    ["Pai", "Father"],
    ["Filho", "Son"],
    ["Filha", "Daughter"],
    ["Irmão", "Brother"],
    ["Irmã", "Sister"],
    ["Avô", "Grandfather"],
    ["Avó", "Grandmother"],
    ["Tio", "Uncle"],
    ["Tia", "Aunt"],
    ["Primo", "Cousin (m)"],
    ["Prima", "Cousin (f)"],
    ["Sobrinho", "Nephew"],
    ["Sobrinha", "Niece"],
    ["Marido", "Husband"],
    ["Esposa", "Wife"],
    ["Bebê", "Baby"],
    ["Criança", "Child"],
    ["Pais", "Parents"],
    ["Sogro", "Father-in-law"],
    ["Sogra", "Mother-in-law"],
    ["Cunhado", "Brother-in-law"],
    ["Cunhada", "Sister-in-law"],
    ["Genro", "Son-in-law"],
    ["Nora", "Daughter-in-law"],
    ["Neto", "Grandson"],
    ["Neta", "Granddaughter"],
    ["Parente", "Relative"]
  ],
  "Body Parts": [
    ["Cabeça", "Head"],
    ["Olho", "Eye"],
    ["Ouvido", "Ear (inner)"],
    ["Nariz", "Nose"],
    ["Boca", "Mouth"],
    ["Dente", "Tooth"],
    ["Língua", "Tongue"],
    ["Rosto", "Face"],
    ["Pescoço", "Neck"],
    ["Ombro", "Shoulder"],
    ["Braço", "Arm"],
    ["Cotovelo", "Elbow"],
    ["Mão", "Hand"],
    ["Dedo", "Finger"],
    ["Unhas", "Nails"],
    ["Peito", "Chest"],
    ["Barriga", "Belly"],
    ["Costa", "Back"],
    ["Perna", "Leg"],
    ["Joelho", "Knee"],
    ["Pé", "Foot"],
    ["Calcanhar", "Heel"],
    ["Coração", "Heart"],
    ["Pulmão", "Lung"],
    ["Estômago", "Stomach"],
    ["Cabelo", "Hair"],
    ["Pele", "Skin"],
    ["Osso", "Bone"],
    ["Sangue", "Blood"],
    ["Músculo", "Muscle"]
  ],
  "Food & Drinks": [
    ["Arroz", "Rice"],
    ["Feijão", "Beans"],
    ["Pão", "Bread"],
    ["Carne", "Meat"],
    ["Frango", "Chicken"],
    ["Peixe", "Fish"],
    ["Ovo", "Egg"],
    ["Queijo", "Cheese"],
    ["Leite", "Milk"],
    ["Manteiga", "Butter"],
    ["Sal", "Salt"],
    ["Açúcar", "Sugar"],
    ["Café", "Coffee"],
    ["Chá", "Tea"],
    ["Suco", "Juice"],
    ["Cerveja", "Beer"],
    ["Vinho", "Wine"],
    ["Maçã", "Apple"],
    ["Banana", "Banana"],
    ["Laranja", "Orange (fruit)"],
    ["Uva", "Grape"],
    ["Morango", "Strawberry"],
    ["Almoço", "Lunch"],
    ["Jantar", "Dinner"],
    ["Café da manhã", "Breakfast"],
    ["Restaurante", "Restaurant"],
    ["Cardápio", "Menu"],
    ["Conta", "Bill"],
    ["Fome", "Hunger"],
    ["Sede", "Thirst"],
    ["Delicioso", "Delicious"],
    ["Batata", "Potato"],
    ["Tomate", "Tomato"],
    ["Cebola", "Onion"],
    ["Alho", "Garlic"],
    ["Fruta", "Fruit"],
    ["Legume", "Vegetable"],
    ["Sobremesa", "Dessert"],
    ["Bolo", "Cake"]
  ],
  "Animals": [
    ["Cachorro", "Dog"],
    ["Gato", "Cat"],
    ["Pássaro", "Bird"],
    ["Peixe", "Fish"],
    ["Cavalo", "Horse"],
    ["Vaca", "Cow"],
    ["Porco", "Pig"],
    ["Galinha", "Hen/Chicken"],
    ["Coelho", "Rabbit"],
    ["Rato", "Mouse/Rat"],
    ["Cobra", "Snake"],
    ["Leão", "Lion"],
    ["Tigre", "Tiger"],
    ["Urso", "Bear"],
    ["Elefante", "Elephant"],
    ["Macaco", "Monkey"],
    ["Girafa", "Giraffe"],
    ["Zebra", "Zebra"],
    ["Lobo", "Wolf"],
    ["Raposa", "Fox"],
    ["Pato", "Duck"],
    ["Peru", "Turkey"],
    ["Abelha", "Bee"],
    ["Borboleta", "Butterfly"],
    ["Aranha", "Spider"],
    ["Formiga", "Ant"],
    ["Mosca", "Fly"],
    ["Animal", "Animal"],
    ["Bicho", "Bug/creature"],
    ["Papagaio", "Parrot"]
  ],
  "House & Home": [
    ["Casa", "House"],
    ["Apartamento", "Apartment"],
    ["Quarto", "Bedroom"],
    ["Banheiro", "Bathroom"],
    ["Cozinha", "Kitchen"],
    ["Sala", "Living room"],
    ["Janela", "Window"],
    ["Porta", "Door"],
    ["Teto", "Ceiling"],
    ["Chão", "Floor"],
    ["Parede", "Wall"],
    ["Escada", "Stairs"],
    ["Garagem", "Garage"],
    ["Jardim", "Garden"],
    ["Cama", "Bed"],
    ["Mesa", "Table"],
    ["Cadeira", "Chair"],
    ["Sofá", "Sofa"],
    ["Televisão", "TV"],
    ["Geladeira", "Refrigerator"],
    ["Fogão", "Stove"],
    ["Armário", "Wardrobe/Closet"],
    ["Espelho", "Mirror"],
    ["Lâmpada", "Lamp"],
    ["Toalha", "Towel"],
    ["Travesseiro", "Pillow"],
    ["Cobertor", "Blanket"],
    ["Chave", "Key"],
    ["Quintal", "Backyard"],
    ["Varanda", "Balcony"]
  ],
  "Clothing": [
    ["Camisa", "Shirt"],
    ["Calça", "Pants"],
    ["Vestido", "Dress"],
    ["Saia", "Skirt"],
    ["Sapato", "Shoe"],
    ["Tênis", "Sneaker"],
    ["Meia", "Sock"],
    ["Casaco", "Coat/Jacket"],
    ["Suéter", "Sweater"],
    ["Camiseta", "T-shirt"],
    ["Bermuda", "Shorts"],
    ["Jaqueta", "Jacket"],
    ["Gravata", "Tie"],
    ["Cinto", "Belt"],
    ["Chapéu", "Hat"],
    ["Boné", "Cap"],
    ["Óculos", "Glasses"],
    ["Bolsa", "Bag/Purse"],
    ["Mochila", "Backpack"],
    ["Luva", "Glove"],
    ["Cachecol", "Scarf"],
    ["Roupa", "Clothes/Clothing"],
    ["Pijama", "Pajamas"],
    ["Cueca", "Underwear (m)"],
    ["Calcinha", "Underwear (f)"],
    ["Sutiã", "Bra"],
    ["Uniforme", "Uniform"],
    ["Botão", "Button"],
    ["Bolso", "Pocket"],
    ["Tamanho", "Size"]
  ],
  "Transportation": [
    ["Carro", "Car"],
    ["Ônibus", "Bus"],
    ["Metrô", "Subway"],
    ["Trem", "Train"],
    ["Avião", "Airplane"],
    ["Bicicleta", "Bicycle"],
    ["Moto", "Motorcycle"],
    ["Barco", "Boat"],
    ["Taxi", "Taxi"],
    ["Caminhão", "Truck"],
    ["Aeroporto", "Airport"],
    ["Estação", "Station"],
    ["Rua", "Street"],
    ["Avenida", "Avenue"],
    ["Semáforo", "Traffic light"],
    ["Pedestre", "Pedestrian"],
    ["Passageiro", "Passenger"],
    ["Motorista", "Driver"],
    ["Viagem", "Trip/Travel"],
    ["Passagem", "Ticket"],
    ["Mapa", "Map"],
    ["Gasolina", "Gas/Gasoline"],
    ["Parada", "Stop"],
    ["Destino", "Destination"],
    ["Direção", "Direction"],
    ["Esquerda", "Left"],
    ["Direita", "Right"],
    ["Em frente", "Straight ahead"],
    ["Trânsito", "Traffic"],
    ["Estrada", "Road/Highway"]
  ],
  "Nature": [
    ["Sol", "Sun"],
    ["Lua", "Moon"],
    ["Estrela", "Star"],
    ["Céu", "Sky"],
    ["Nuvem", "Cloud"],
    ["Chuva", "Rain"],
    ["Vento", "Wind"],
    ["Neve", "Snow"],
    ["Fogo", "Fire"],
    ["Terra", "Earth/Land"],
    ["Mar", "Sea"],
    ["Rio", "River"],
    ["Lago", "Lake"],
    ["Montanha", "Mountain"],
    ["Floresta", "Forest"],
    ["Praia", "Beach"],
    ["Areia", "Sand"],
    ["Pedra", "Stone/Rock"],
    ["Árvore", "Tree"],
    ["Flor", "Flower"],
    ["Planta", "Plant"],
    ["Grama", "Grass"],
    ["Folha", "Leaf"],
    ["Raiz", "Root"],
    ["Calor", "Heat"],
    ["Tempestade", "Storm"],
    ["Arco-íris", "Rainbow"],
    ["Natureza", "Nature"]
  ],
  "Common Adverbs & Prepositions": [
    ["Aqui", "Here"],
    ["Lá/Ali", "There"],
    ["Perto", "Near/Close"],
    ["Longe", "Far"],
    ["Dentro", "Inside"],
    ["Fora", "Outside"],
    ["Em cima", "On top/Above"],
    ["Embaixo", "Below/Under"],
    ["Antes", "Before"],
    ["Depois", "After"],
    ["Sempre", "Always"],
    ["Nunca", "Never"],
    ["Às vezes", "Sometimes"],
    ["Muito", "Very/A lot"],
    ["Pouco", "A little"],
    ["Mais", "More"],
    ["Menos", "Less"],
    ["Também", "Also/Too"],
    ["Só/Apenas", "Only/Just"],
    ["Já", "Already"],
    ["Ainda", "Still/Yet"],
    ["Logo", "Soon"],
    ["Talvez", "Maybe"],
    ["Sim", "Yes"],
    ["Não", "No"],
    ["Com", "With"],
    ["Sem", "Without"],
    ["Para", "For/To"],
    ["De", "Of/From"],
    ["Em", "In/On/At"]
  ],
  "More Question Words": [
    ["O que?", "What?"],
    ["Quem?", "Who?"],
    ["Onde?", "Where?"],
    ["Quando?", "When?"],
    ["Por que?", "Why?"],
    ["Como?", "How?"],
    ["Quanto?", "How much?"],
    ["Quantos?", "How many?"],
    ["Qual?", "Which?"],
    ["De onde?", "From where?"],
    ["Para onde?", "Where to?"],
    ["Com quem?", "With whom?"],
    ["O que é isso?", "What is this?"],
    ["Qual é o preço?", "What's the price?"],
    ["Quanto custa?", "How much does it cost?"],
    ["Onde fica?", "Where is it located?"],
    ["A que horas?", "At what time?"],
    ["Quem é?", "Who is it?"],
    ["Por quê?", "Why? (end of sentence)"],
    ["Como se chama?", "What is your name?"]
  ],
  "City & Places": [
    ["Cidade", "City"],
    ["Bairro", "Neighborhood"],
    ["Hospital", "Hospital"],
    ["Farmácia", "Pharmacy"],
    ["Banco", "Bank"],
    ["Supermercado", "Supermarket"],
    ["Loja", "Store/Shop"],
    ["Mercado", "Market"],
    ["Igreja", "Church"],
    ["Parque", "Park"],
    ["Praça", "Square/Plaza"],
    ["Biblioteca", "Library"],
    ["Cinema", "Movie theater"],
    ["Teatro", "Theater"],
    ["Hotel", "Hotel"],
    ["Pousada", "Inn"],
    ["Prédio", "Building"],
    ["Correio", "Post office"],
    ["Delegacia", "Police station"],
    ["Posto de gasolina", "Gas station"],
    ["Shopping", "Mall"],
    ["Padaria", "Bakery"],
    ["Açougue", "Butcher shop"],
    ["Salão", "Salon"],
    ["Oficina", "Workshop/Repair shop"],
    ["Feira", "Fair/Market"],
    ["Museu", "Museum"],
    ["Estádio", "Stadium"],
    ["Rodoviária", "Bus terminal"]
  ],
  "School & Education": [
    ["Professor/a", "Teacher"],
    ["Aluno/a", "Student"],
    ["Sala de aula", "Classroom"],
    ["Quadro", "Blackboard"],
    ["Caderno", "Notebook"],
    ["Caneta", "Pen"],
    ["Lápis", "Pencil"],
    ["Borracha", "Eraser"],
    ["Régua", "Ruler"],
    ["Prova", "Test/Exam"],
    ["Tarefa", "Homework/Task"],
    ["Nota", "Grade/Note"],
    ["Aula", "Class/Lesson"],
    ["Recreio", "Recess"],
    ["Dicionário", "Dictionary"],
    ["Matemática", "Math"],
    ["Português", "Portuguese"],
    ["História", "History"],
    ["Ciência", "Science"],
    ["Arte", "Art"],
    ["Música", "Music"],
    ["Educação Física", "Physical Education"],
    ["Formatura", "Graduation"],
    ["Faculdade", "College/University"],
    ["Diploma", "Diploma"]
  ],
  "Health & Body": [
    ["Saúde", "Health"],
    ["Doença", "Illness/Disease"],
    ["Dor", "Pain"],
    ["Febre", "Fever"],
    ["Tosse", "Cough"],
    ["Resfriado", "Cold (illness)"],
    ["Gripe", "Flu"],
    ["Remédio", "Medicine"],
    ["Médico", "Doctor"],
    ["Enfermeiro/a", "Nurse"],
    ["Consulta", "Appointment"],
    ["Receita", "Prescription/Recipe"],
    ["Cirurgia", "Surgery"],
    ["Alergia", "Allergy"],
    ["Vacina", "Vaccine"],
    ["Acidente", "Accident"],
    ["Emergência", "Emergency"],
    ["Ambulância", "Ambulance"],
    ["Plano de saúde", "Health insurance"],
    ["Bem-estar", "Well-being"],
    ["Exercício", "Exercise"],
    ["Dieta", "Diet"],
    ["Descanso", "Rest"],
    ["Sono", "Sleep"],
    ["Estresse", "Stress"],
    ["Cansaço", "Fatigue"],
    ["Fratura", "Fracture"],
    ["Pressão alta", "High blood pressure"],
    ["Diabetes", "Diabetes"]
  ],
  "Technology & Communication": [
    ["Celular", "Cell phone"],
    ["Computador", "Computer"],
    ["Internet", "Internet"],
    ["E-mail", "Email"],
    ["Mensagem", "Message"],
    ["Redes sociais", "Social media"],
    ["Foto", "Photo"],
    ["Vídeo", "Video"],
    ["Aplicativo", "App"],
    ["Senha", "Password"],
    ["Teclado", "Keyboard"],
    ["Mouse", "Mouse"],
    ["Tela", "Screen"],
    ["Impressora", "Printer"],
    ["Câmera", "Camera"],
    ["Carregador", "Charger"],
    ["Bateria", "Battery"],
    ["Wi-Fi", "Wi-Fi"],
    ["Download", "Download"],
    ["Upload", "Upload"],
    ["Rádio", "Radio"],
    ["Telefone", "Telephone"],
    ["Ligação", "Call/Phone call"],
    ["Notificação", "Notification"],
    ["Arquivo", "File"],
    ["Pasta", "Folder"],
    ["Rede", "Network"],
    ["Tecnologia", "Technology"]
  ],
  "Emotions & Feelings": [
    ["Raiva", "Anger"],
    ["Medo", "Fear"],
    ["Amor", "Love"],
    ["Ódio", "Hate"],
    ["Alegria", "Joy"],
    ["Saudade", "Longing/Missing"],
    ["Surpresa", "Surprise"],
    ["Vergonha", "Shame/Embarrassment"],
    ["Orgulho", "Pride"],
    ["Inveja", "Envy"],
    ["Ansiedade", "Anxiety"],
    ["Paz", "Peace"],
    ["Esperança", "Hope"],
    ["Decepção", "Disappointment"],
    ["Gratidão", "Gratitude"],
    ["Ciúme", "Jealousy"],
    ["Confiança", "Trust/Confidence"],
    ["Solidão", "Loneliness"],
    ["Entusiasmo", "Enthusiasm"],
    ["Carinho", "Affection"],
    ["Compaixão", "Compassion"],
    ["Empolgação", "Excitement"],
    ["Nervoso", "Nervous"],
    ["Preocupado", "Worried"],
    ["Aliviado", "Relieved"],
    ["Confuso", "Confused"],
    ["Curioso", "Curious"]
  ],
  "Work & Professions": [
    ["Emprego", "Employment/Job"],
    ["Salário", "Salary"],
    ["Chefe", "Boss"],
    ["Funcionário", "Employee"],
    ["Empresa", "Company"],
    ["Escritório", "Office"],
    ["Reunião", "Meeting"],
    ["Projeto", "Project"],
    ["Advogado", "Lawyer"],
    ["Engenheiro", "Engineer"],
    ["Cozinheiro", "Cook/Chef"],
    ["Policial", "Police officer"],
    ["Bombeiro", "Firefighter"],
    ["Vendedor", "Salesperson"],
    ["Arquiteto", "Architect"],
    ["Contador", "Accountant"],
    ["Dentista", "Dentist"],
    ["Ator/Atriz", "Actor/Actress"],
    ["Músico", "Musician"],
    ["Programador", "Programmer"],
    ["Fotógrafo", "Photographer"],
    ["Jornalista", "Journalist"],
    ["Piloto", "Pilot"],
    ["Mecânico", "Mechanic"],
    ["Agricultor", "Farmer"]
  ],
  "Shopping": [
    ["Preço", "Price"],
    ["Caro", "Expensive"],
    ["Barato", "Cheap"],
    ["Desconto", "Discount"],
    ["Promoção", "Sale/Promotion"],
    ["Cartão", "Card"],
    ["Troco", "Change (money)"],
    ["Recibo", "Receipt"],
    ["Nota fiscal", "Invoice"],
    ["Cliente", "Customer"],
    ["Cor", "Color"],
    ["Produto", "Product"],
    ["Marca", "Brand"],
    ["Qualidade", "Quality"],
    ["Estoque", "Stock"],
    ["Vitrine", "Display window"],
    ["Etiqueta", "Tag/Label"],
    ["Sacola", "Shopping bag"],
    ["Carrinho", "Cart"],
    ["Caixa", "Cashier/Box"],
    ["Fila", "Line/Queue"],
    ["Trocar", "To exchange"],
    ["Devolver", "To return"]
  ],
  "Weather & Seasons": [
    ["Tempo", "Weather/Time"],
    ["Estação", "Season"],
    ["Verão", "Summer"],
    ["Inverno", "Winter"],
    ["Outono", "Autumn/Fall"],
    ["Primavera", "Spring"],
    ["Morno", "Warm"],
    ["Nublado", "Cloudy"],
    ["Ensolarado", "Sunny"],
    ["Chuvoso", "Rainy"],
    ["Úmido", "Humid"],
    ["Seco", "Dry"],
    ["Ventoso", "Windy"],
    ["Relâmpago", "Lightning"],
    ["Trovão", "Thunder"],
    ["Geada", "Frost"],
    ["Granizo", "Hail"],
    ["Neblina", "Fog/Mist"],
    ["Temperatura", "Temperature"],
    ["Grau", "Degree"],
    ["Previsão", "Forecast"],
    ["Termômetro", "Thermometer"],
    ["Guarda-chuva", "Umbrella"],
    ["Chuva forte", "Heavy rain"],
    ["Brisa", "Breeze"],
    ["Clima", "Climate"]
  ],
  "Sports & Leisure": [
    ["Futebol", "Soccer/Football"],
    ["Vôlei", "Volleyball"],
    ["Basquete", "Basketball"],
    ["Tênis", "Tennis"],
    ["Natação", "Swimming"],
    ["Corrida", "Running"],
    ["Ciclismo", "Cycling"],
    ["Caminhada", "Hiking/Walking"],
    ["Academia", "Gym"],
    ["Jogo", "Game"],
    ["Time", "Team"],
    ["Jogador", "Player"],
    ["Gol", "Goal"],
    ["Placar", "Score"],
    ["Campeonato", "Championship"],
    ["Torneio", "Tournament"],
    ["Treino", "Training"],
    ["Competição", "Competition"],
    ["Férias", "Vacation"],
    ["Passeio", "Outing/Walk"],
    ["Show", "Show/Concert"],
    ["Festa", "Party"],
    ["Jogo de cartas", "Card game"],
    ["Dança", "Dance"],
    ["Leitura", "Reading"],
    ["Hobby", "Hobby"]
  ]
};